### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by PabloRomanH** [photopea/photopea#1067]
Can't use emoji in texts. When using a regular font the emoji appear as squares.
I managed to load an emoji font (Twitter's) but when the font is selected nothing appears in the text.

**Comment by photopea** [comment]
Hi, not all fonts have glyphs for emojis. You have to use a font, that you know has emojis.

[Check this](https://www.photopea.com/?p=%7B%22files%22:%5B%22https://www.photopea.com/api/img2/fnt_preview.psd%22%5D,%22resources%22:%5B%22https://www.photopea.com/api/img2/fnts/Abelone-FREE.otf%22,%22https://www.photopea.com/api/img2/fnts/BungeeColor-Regular_svg.ttf%22,%22https://www.photopea.com/api/img2/fnts/Gilbert-Color%20Bold-Preview_1004.otf%22,%22https://www.photopea.com/api/img2/fnts/NTBixa-Color.otf%22,%22https://www.photopea.com/api/img2/fnts/Playbox-FREE.otf%22%5D,%22environment%22:%7B%7D%7D). The last line (Source Code Pro font) does contain emojis, and they are rendered correctly.

If you use your own font, for which you are sure, that it contains emojis, but emojis are not rendered in Photopea, please, send us your font.

**Comment by PabloRomanH** [comment]
It doesn't work. I've tried uploading the Twitter Color Emoji font, and when inserting emojis it just shows empty spaces.
The font is freely available here: https://github.com/eosrei/twemoji-color-font/releases/download/v11.2.0/TwitterColorEmoji-SVGinOT-11.2.0.zip
The font is in a .ttf file, but it uses the SVGinOT format, if that's any help.

The Source Code Pro font given in the example above does show color for the older B&W icons like the smiley face and the heart, but it also doesn't support any of the modern color emoji.

**Comment by photopea** [comment]
Sorry, but I was not able to use your SVG in Photoshop or any other program. Could you use it in any program to type smileys?

**Comment by PabloRomanH** [comment]
Yes, I'm using it. It's a ttf file. You install it like any other font on your operating system and term you can use it in Photoshop.

**Comment by photopea** [comment]
So there really was a bug with parsing SVG fonts. I just fixed it, it should work well now :)

https://imgur.com/pyeHp5A

**Comment by QuantumInformation** [comment]
I've not had any luck with this, still get the squares when trying to render this:
🚨

**Comment by photopea** [comment]
@QuantumInformation Is your question related to the Twitter font above?  If not, what font are you using? Are you sure it contains glyphs for emojis?

**Comment by QuantumInformation** [comment]
I was trying different fonts. Are there any that support it on your site?

**Comment by photopea** [comment]
If the font supports emoji, it should be rendered. We do not have any switch, that would show you only fonts which include emojis. But we could add such filter.

**Comment by oliverbenns** [comment]
I ended up downloading the image from here and importing: https://emoji.aranja.com/
