### ISSUE TITLE
Unable to tedit text in modern PSD

### ISSUE THREAD

**Issue by photopea** [photopea/photopea#122]
It is not possible to edit text in files such as "OasisFlyer.psd".

**Comment by photopea** [comment]
Fixed.

**Comment by randomd00d** [comment]
Still unable to edit text layers (using latest version of Firefox). It doesn't matter if the text layer is present in an uploaded file, or added into a new one (made with Photopea). Double-clicking on the text layer icon in the layer window (T icon, not the name nor the space to the right of the layer) opens up layer styles.

Right clicking on the the text layer within the layer window does not offer an option to edit text.

**Comment by photopea** [comment]
Hi, to edit text layers, you should choose a Type tool (from the toolbar on the left) and then click once with a left mouse button on the type layer.

If it does not help, can you send us your PSD file to support@photopea.com?

**Comment by randomd00d** [comment]
Works, thanks. I had to click right beneath the text (inside the workarea, not the layers window) I wanted to edit. For some reason, clicking on the layer itself always created a new text layer.

Sorry for the false alarm, it's just that while working in Photoshop, I always edit text layers by double-clicking on them in the layers window. Was expecting the same behaviour here. :)

**Comment by photopea** [comment]
When your text layer cotnains "Hello World" and you click between "W" and "o", the typing cursor should appear between "W" and "o" and you can start typing. Let me know if it does not work this way.

I did not know about that double-clicking feature in Photoshop. But if many users are used to it, we will add it to Photopea too :)  https://github.com/photopea/photopea/issues/150

**Comment by derek-adair** [comment]
Hey i may have accidentally created a perfect testing replica of this bug.  I have a PSD where several text layers are on each side of my image.  The right side is easily editable the left cannot be edited and consistently creates a new text layer.

**Browser**
`Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0`

[PSD](https://file.io/CgQfooj1l2BG)

**Comment by derek-adair** [comment]
For what it's worth deleting the text on the right side and starting over fixed my issue.

**Comment by photopea** [comment]
You have only two text layers (one with "Derekadair.com" three times, one empty). Both of them are editable.

**Comment by photopea** [comment]
You have only two text layers with the same content ("Derekadair.com" three times). One text is white, one black. Both are editable.

**Comment by derek-adair** [comment]
Sorry the uneditable text is on the left not right, the derekadair.com is editable for me as well.  Its the D@/Services./Blog part.  I uploaded a simpler copy with two layers [to my s3 ](https://projectderleek.s3.amazonaws.com/bidness+card+2022(1).psd)for more permanent access.  Let me know if you are unable to replicate this.

**Comment by derek-adair** [comment]
Honestly the other bug i submitted was the bigger of the two i ran into, i cant even figure out how I got the text to this state and cant replicate it. Could have something to do with;

1. Duplicating text
2. Right aligned text
3. text boxes with carriage returns

Really probably not worth chasing down... but maybe just interesting.

**Comment by photopea** [comment]
Your new PSD does not contain any text layers. If you paint the word HELLO with a brush tool, you can not expect to edit it with a Type tool.

You can rasterize a text layer to convert it to a regular pixel layer (you can paint into pixel layers, but not into text layers).

**Comment by derek-adair** [comment]
Good lord.  I rasterized it.

![image](https://user-images.githubusercontent.com/847236/187178458-d329dd75-1b22-4478-a09f-26de4284e981.png)
