### ISSUE TITLE
Colorpicker panel - pick color from swatches palette

### ISSUE THREAD

**Issue by mikelchris** [photopea/photopea#1242]
Hi, 
Is it possible to build in the following function?

I would like to change the color of the color picker panel through selecting the color within the color swatches panel.

![image](https://user-images.githubusercontent.com/5864130/53244968-a7dc0580-36ac-11e9-9599-02f8cd096311.png)

Thanks!

Michael

**Comment by joshmorel** [comment]
I was just about to open a new issue that was similar to this so I will just post here. The issue I was going to call is "Color History in Color Picker, Swatches and Shape Fill" do not match. If I want to work with a palette of limited colors this seems like have a "global" history that is consistent across any tool with a color history is a good choice.

I'd love to hear comments from others however, especially those with significant experience using similar tools.


As you see below the three histories do not match:
![photopea-color-histories-dont-match](https://user-images.githubusercontent.com/10546720/53586292-d4cd6400-3b55-11e9-9e06-df2cb655958e.png)

**Comment by photopea** [comment]
Hi, I fixed both issues.

Whenever the foreground color is changed (e.g. by clicking in Swatches), Color Picker updates the current color. Both Swatches and Color Picker show the same history of foreground colors.

**Comment by joshmorel** [comment]
Awesome thanks for the quick update. I see color picker history and swatches history aligned, however, I still see the shape fill and stroke fill are not aligned. Or is there a reason not to do this?

![photopea-shape-fill-vs-swatch-color-history](https://user-images.githubusercontent.com/10546720/53596935-f25af780-3b6e-11e9-9544-39a222178ec8.png)
