### ISSUE TITLE
Color changes after exporting to PDF

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1319]
This have had a huge impact on my company.

I sent to print 3.000 units of a box, and they came in a different color.

After discussion for a while with the printing company, i discovered that when exporting the proyects to PDF they change the colors!

Please take a look to this banana and its preview 
![Screenshot 2019-04-02 at 01 32 54](https://user-images.githubusercontent.com/11801254/55376688-e18fff80-54e7-11e9-85e3-66bbe932aa71.png)

One have way more green on the yellow than the other.

i cannot use the PDF a stable solutions for exporting if this keeps happening.

Please, please take this issue as urgent.

Cheers!

**Comment by photopea** [comment]
HI Alvaro, can you show me the original file (e.g. as PSD), so I can convert it to PDF myself and see what happens?

**Comment by avagp** [comment]
Here
[Caja Platano (1) (1).zip](https://github.com/photopea/photopea/files/3036715/Caja.Platano.1.1.zip)

**Comment by photopea** [comment]
So when I do the same with your PSD, here is what I see: 

![image](https://user-images.githubusercontent.com/15955558/55486406-916e8580-562c-11e9-9472-aba742dc093c.png)

The color difference is at most 1 in every channel (e.g. 200 of green vs. 201 of green). I can fix this difference.

In your case, the PDF preview is a lot different. Also, the "left yellow" is darker in your case, while the "right yellow" is darker in my case.

Did you send me the right PSD file?

**Comment by photopea** [comment]
If it really is the right PSD, I think your device is doing incorrect color space conversions on multiple levels. It could be the browser, the PDF viewer, the OS, etc. 

You can think of it like this: The file says a stick is 30 cm long. You open it in Program A, which has a bug and reads it as 30 inches long. Then, the Program A saves a stick as new file, and correctly saves 30 inches as 75 cm.  Then, you open the old stick and a new stick in a Program B, and they have different lengths, but it was the same stick originally.

So "cm" is like sRGB, and "inches" are like Adobe RGB. There exist many other color spaces (units of color).

**Comment by avagp** [comment]
It is the file. In case is different i am attaching it again:
[Platano Box.zip](https://github.com/photopea/photopea/files/3040748/Platano.Box.zip)

I still get it. I am on chrome stable, running on a chromebook. So i am using the PDFViewer from Google
![Screenshot 2019-04-03 at 18 09 09](https://user-images.githubusercontent.com/11801254/55513377-e36ad780-563b-11e9-8afc-1796ce6e4f61.png)

**Comment by avagp** [comment]
I have tried in another PDF and the colors are right.

Also when opening the exported PDF on Photopea it get the correct colors as well.

Though, after exporting to PDF, the colors changes a little. For example the yellow of the box is 255, 215,0 and after exporting it becomes 255,214,0 (and i see that color code on every plastform, even the same photopea)

So, it is a Chrome PDF viewer problem. 

Would you like to report it to the chromium bug tracker?

**Comment by photopea** [comment]
Hey, so I fixed the problem with these tiny differences (215 vs. 214). 

So I guess your previous large color difference was in Chrome Beta, but now, everything should look correct in a stable version, right?

**Comment by avagp** [comment]
No, I still see the difference between 215 and 214, i have just tried.
(export to pdf, then open in photopea and check the RGB color)

Also, the color changes on the PDF viewer are still there, even after changing to stable channel.

Even though, it is important for me to have my work properly exposed on a PDF, is more important to have it properly displayed on a editing software.

Today i tried to open it on Adobe Ilustrator and i got 214.
![image](https://user-images.githubusercontent.com/11801254/55587661-34dd9a00-5702-11e9-8da7-54e2fc419d25.png)

Could you check again the fix please?  :)

**Comment by photopea** [comment]
I opened your latest PSD  "Platano Box.psd". The yellow color of the box is (255,215,0) - both Photopea and Photoshop say the same color. Then, I press File - Export As - PDF, I see a preview of PDF (still in Chrome). I take a screenshot. In the screenshot,the yellow color is still (255,215,0)

What exactly did you do in your case to get 214?

**Comment by photopea** [comment]
Oh, I see. When I save PDF from Photopea, and load it into Photopea again, I get 214 :dagger: 

So the problem is not in PDF export, but in PDF import :D

**Comment by avagp** [comment]
Exactly!

But have you opened the PDF after exported in Google Chrome (the nvative PDF Viewer)?

Because i see this, and does not have the same color!
![image](https://user-images.githubusercontent.com/11801254/55588560-77a07180-5704-11e9-9a18-d2d76b0a85c7.png)

**Comment by photopea** [comment]
What banana file are you using? What is the value of the bright yellow color in your banana?

In the old banana, that you send me, I see (237,211,48). 

The bananas in your screenshot have (255,210,64) on the left and (255,214,0) on the right. 

So there is probably a bug in your printscreen program, too. 

Please, check the color value that you see in Photopea with the value of what you see in your screenshot. I think there may be errors in multiple steps, we should check it step by step.

**Comment by avagp** [comment]
Right now, if i set a color code, then export it to PDF, then import that PDF again to Photopea, the color codes are kept without any issue.

When opening the PDF on Chrome Viewer i get another values.
When opening the PDF on other editing programs (like ilustrator or photoshop) i get the correct values.
When opening the PDF on other PDF viewers (like acrobat or this http://pdfviewer.softgateon.net/) i get the correct values.

So is chrome PDF viewer. I reported as a bug on the chromium project, you can follow it here:
https://bugs.chromium.org/p/chromium/issues/detail?id=949846

**Comment by photopea** [comment]
I never heard about "Chrome PDF Viewer", that you are mentioning. Is it something specific to Chrome OS? There is probably no way I can reproduce it on Windows. I see correct color values inside Google Chrome browser, which has a built-in PDF viewer based on PDF.js project.

Are there any settings in that "Chrome PDF Viewer"? Could you try to change color profiles or something?

**Comment by photopea** [comment]
So I think the problem is outside Photopea, so I will close it now.
