### ISSUE TITLE
Actions won't create or execute correctly

### ISSUE THREAD

**Issue by leaptrotaj** [photopea/photopea#1350]
When trying to create an action, some steps like "duplicate layer" are skipped while others are recorded. After creating an action or importing from photoshop, the action will not execute, but rather freezes the window.

**Comment by photopea** [comment]
Hi, not all actions are playable / recordable at the moment. But we extend them gradually. Do you have an ATN file, which you need to execute? We would like to focus on frequently used actions first.

**Comment by leaptrotaj** [comment]
Attached is the atn from photoshop that I would like to use. 


Thanks,

**Comment by photopea** [comment]
Sorry, I did not receive anything :( could you please reply directly on GitHub?

**Comment by photopea** [comment]
I have to close it because of lack of details :(

**Comment by leaptrotaj** [comment]
Apologies, I didn’t check my emails over the weekend. 

Is this able to be reopened?

**Comment by leaptrotaj** [comment]
[Low Poly.zip](https://github.com/photopea/photopea/files/3103974/Low.Poly.zip)

**Comment by photopea** [comment]
Hi, I fixed the problem with your action. Note, that when you apply it, there has to be a layer named "Background" (which is usually made automatically when you open a regular image) and there should be a selection.

**Comment by leaptrotaj** [comment]
I’m still unable to add “Duplicate Layer” to actions. The rest seems to be working well though

**Comment by photopea** [comment]
Hi, I fixed the problem. You can record a Duplicate action in Photopea now.
