### ISSUE TITLE
Perspective Crop not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1354]
Perspective Crop seems to be not working see screenshots:

![pbefore](https://user-images.githubusercontent.com/6370548/56454561-12c75700-6353-11e9-88da-d03a87d71bbc.png)

![pafter](https://user-images.githubusercontent.com/6370548/56454560-12c75700-6353-11e9-9301-73570f6901b0.png)

**Comment by photopea** [comment]
It is a very interesting case. The Crop tool applies a Perspective Free Transform (the one, where each corner can be dragged separately) to a whole layer. Then, it just crops the result.

If you try to stretch your whole layer manually with a Free Transform, you will see, that it is not possible. It is not possible, when the "infinity point" (where parallel lines meet) lies inside the image. I will have to remake this part tomorrow.

**Comment by photopea** [comment]
It was fixed. Thanks for reporting!

**Comment by hxim** [comment]
It is still not working :((((
![pbefore](https://user-images.githubusercontent.com/6370548/56556562-9cb43180-6598-11e9-83a8-058ed27d638e.png)

![pafter](https://user-images.githubusercontent.com/6370548/56556561-9cb43180-6598-11e9-99b9-d94d7264d034.png)

**Comment by photopea** [comment]
So there was another limitation. The perspective transform (used inside Perspective crop) did not work, if the width or the height of the result is larger than 30 000 pixels (to prevent going out of memory).

I think it was your case. I changed the limit to 100 000 pixels. It should work now.

**Comment by hxim** [comment]
Hello now it works most of the time but not always. When I move buttom right corner straight up (zero pixel left or right) as in screenshot everything disappears.
![pbefore](https://user-images.githubusercontent.com/6370548/56656490-f2bacf00-6695-11e9-98c7-f0753c74db2f.png)
![pafter](https://user-images.githubusercontent.com/6370548/56656489-f2bacf00-6695-11e9-829f-c7b64aab0ec9.png)

**Comment by photopea** [comment]
That is a strange bug :/

**Comment by photopea** [comment]
Hey, I just tried it several times and it works well in my case. Could you try to find exact coordinates, for which it happens? You can use Guides to help you find such coordinates.

**Comment by hxim** [comment]
Sure.
Open photopea and pea.psd. Open info window so you can see X and Y of your mouse.
Select Perspective Crop tool.
Move cursor to X:33 Y:128
Hold left mouse buton and move mouse to X:268 Y:372
Release your left mouse button.
Hold left mouse button again and move mouse to X:268 Y:332
Release your left mouse button.
Confirm Perspective Crop.
Everything disappears...

**Comment by photopea** [comment]
Hi, I tried it, but it still works fine in my case :/  https://i.imgur.com/IquMDR4.png

Here is my pea.psd with guides according to your coordinates.
[pea.zip](https://github.com/photopea/photopea/files/3117033/pea.zip)

**Comment by hxim** [comment]
Hello If I do it with guides it works for me too. I think it is because after you I move bottom right corner it is not on exact integer coordinates but in between two pixels. See how it is positioned when done without guides (to see the bug) on this screenshot.
![bug](https://user-images.githubusercontent.com/6370548/56743557-0f7b0380-6777-11e9-83e0-f6b9ef0f329d.png)

**Comment by photopea** [comment]
There is quite a complex task in the Perspective Crop. You have to guess the aspect ratio of the original rectangle (i.e. the aspect ratio of what you get after cropping).

The thing is, your quadrilateral does not correspond to a real 3D rectangle in space. If the top-left and top-right corners should be 90 degrees, the top edge should be vertically at the center of the screen. Our aspect-ratio-guessing method had problems with this input, and divided by zero.

Now, if aspect-ratio-guessing method returns NaN or Infinity, we make a new guess of the aspect ratio as the average of lengths of opposite sides of quadrilateral.
