### ISSUE TITLE
Warp problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1411]
1. Open pea.psd (you have "Welcome" layer selected)
2. Select Type Tool
3. Click "Warp" button
4. Click on "17%" value  next to "Bend:" label
    or
    Click on "42 px" value  next to "Size:" label
5. Press arrow UP two times
-> Error
pp.js:3654 Uncaught TypeError: Cannot read property 'JV' of undefined
    at $.Sy.hEG (pp.js:3654)

**Comment by photopea** [comment]
Hi, I fixed it, thanks! :)

**Comment by hxim** [comment]
Hello you fixed only the first variant (Click on "17%" value next to "Bend:" label)
but when you click on "42 px" value next to "Size:" label in top toolbar in 4.) there is still error
pp.js:3654 Uncaught TypeError: Cannot read property 'nH' of undefined
    at I.bn.pRs (pp.js:3654)

**Comment by photopea** [comment]
it was fixed, too.

**Comment by hxim** [comment]
Hello I found out it still crashes if you do one of the following:
1. Open pea.psd (you have "Welcome" layer selected)
2. Select Type Tool
3. Click "Warp" button
4. Open Color Picker to change text color
5. Press arrow UP on keyboard (or SHIFT+arrow RIGHT)
or 
1. Open pea.psd (you have "Welcome" layer selected)
2. Select Type Tool
3. Click "Warp" button
4. Change font in top toolbar
5. Press arrow UP on keyboard (or SHIFT+arrow RIGHT)

**Comment by photopea** [comment]
I think I fixed it. Thanks!
