### ISSUE TITLE
List of keyboard shortcuts

### ISSUE THREAD

**Issue by wernight** [photopea/photopea#154]
Commonly pressing Ctrl + ? shows a list of keyboard shortcut, but there is also often a menu item to show them or a ? icon. I didn't find a list of keyboard shortcuts especially for things that have no tooltip like:

  - Swapping foreground/background colors
  - Changing brush size
  - Zoom
  - ...

**Comment by photopea** [comment]
I am sorry, there is no up-to-date list of currently supported shortcuts. We add them gradually.

There are probably two ways to go. First, we can implement our own shortcuts. Or we can implement the "familiar" shortcuts of Photoshop or some other program and refer to the Photoshop manuals for shortcuts.

Or we can make adjustable shortcuts, so users can chage them ... what do you think about the idea, that users can change shortcuts?

**Comment by wernight** [comment]
I feel **adjustable is overkill** and most users wouldn't change. They might tweak from a base familiar preset if one shortcut doesn't work well on their OS but that means that this shortcut is probably wrong and should be changed to something else by default.

Personally I'm also used to **Photoshop shortcuts** and those are my first reflex, but I imagine someone being used to GIMP trying those shortcuts instead. It looks like many GIMP (new) users are [looking for Photoshop shortcuts](http://epierce.freeshell.org/gimp/gimp_ps.php) as well, so I'd tend to go with Photoshop (**the "standard"**) shortcuts when possible, with alternatives to:

 - Cover commonly infeasible shortcuts e.g. cannot do Ctrl + W in a standard browser window (it'd close the tab)
 - Provide an alternative for common editors, e.g. you might allow P for brush (GIMP) as well as B (Photoshop).

Might consider looking a PaintShop Pro shortcuts as well as it a common tool, just may be its target is mostly people that are less likely to switch to web technologies soon.

One last point to support PS shortcuts is **Pixlr** editor (currently Flash-only so dead for now) but it's famous, and even thought it's bought/made by Adobe, being famous people may know its shortcuts which are mostly those of PS but ported for web compatibility (sometimes still not fully compatible). So you may want into those as a good **starting point**.

**Comment by photopea** [comment]
Thank you @wernight  for such a long comment.

I will go with adopting Photoshop's shortcuts. Some of PS shortcuts are not available, because PP does not have such tool or feature yet. But if it does, I would like people to point it out to me (I am not a designer and I don't know all PS shortcuts). E.g. today I have added Ctrl+J .

Pixlr was not made or bought by Adobe. It was bought by Autodesk many years ago. Sortcuts in Pixlr are almost the same as in Photoshop.

Browsers have much more problems than just Ctrl+W . It is Ctrl+N for a new document or Ctrl+T for free transform. In Chrome OS, clicking with Alt causes a right mouse click, so Alt+Ctrl+Space+Click is not possible for zooming out, or Alt + Click to choose a source for Clone Tool. Browser vendors know about these problems for many years, but they still haven't come up with a solution. I guess that Photopea will have to start developing our own web browser.

So please reopen this and tell me, which specific shortcuts do you miss. Brush size shortcuts are the same as in PS.

**Comment by wernight** [comment]
Thanks very nice already. You're right I mixed up in my memory and memorize Adobe instead of Autodesk. Also agree that there are many more issues which is why I thought Pixlr might be a good candidate to look at used shortcuts.

I'm missing:

 - Zooming/moving around (IMO critical especially on laptops):
     - Zooming if I remember is possible on PS using Space + Wheel. Even if not, I'd consider it as Ctrl/Alt+Space don't play that well on browser apps.
     - [Mouse middle can be used to move around](https://forums.adobe.com/thread/511886) (for desktop/mouse).
     - When zoomed in and while using for example the selection/crop tool, in PS I can hold space to move around and precisely crop on a large image. I forgot if it does, but auto-scrolling when near or outside of the image area should also be a nice add-on for that.
 - **D** to reset to default foreground/background colors to back and white respectively.
 - **X** to swap foreground/background colors (black and white by default)
 - Ctrl+T not working in browser tab (may be look at https://stackoverflow.com/questions/7295508/javascript-capture-browser-shortcuts-ctrlt-n-w)
 - Shift/Alt when resizing (from selection tool to feel transform) to constrain size or make it symmetric

**Comment by wernight** [comment]
Issues on Chromebooks:
 - Tried on my Chromebook and indeed the Alt + Click --> Right click, so cannot zoom out (or doing a hack). I saw [the ticket about this Chrome issue](https://github.com/photopea/photopea/issues/104) but could have alternatives especially on Chromebooks where this is an issue (like pinch, scroll...)
 - Two fingers aren't detected as a zoom/scroll (less important but it's a neat and natural habit of doing it on a touch screen).
 - Ctrl+Alt+Z toggle Chrome Vox (accessibility), so should allow Ctrl + Z to undo or Ctrl+Shift+Z (same of PS even though it's a weird one)

**Comment by photopea** [comment]
You comment chromium bugs without even reading the original bug description.

**Comment by photopea** [comment]
Ok, so the following works the same in PS and PP:
- Turning mouse wheel scrolls the image vertically, with Ctrl horizontally, with Alt it zooms in / out.
- Elliptic and Rectangular Marqueue is constrained with Shift / Alt, the selection can be moved by pressing the Spacebar during drawing
- X swaps foreground / background colors, D resets these colors

Two-finger scrolling on a touchpad is detected on my computer as scrolling. Making Photopea usable without a keyboard would be very hard. Let's postpone it to the future. 
Most of browsers don't let webapps use Ctrl+T, but I have noticed, that if you press Alt+Ctrl+T, Photopea still catches it (because Ctrl and T are pressed), but browsers ignore it.

**Comment by photopea** [comment]
And thank you for writing this requrest. I really appreciate it :)

**Comment by wernight** [comment]
You just made Photopea a lot easier to use.

I tried to break up what looks like harder tasks and kept here a list of what I'd suggest that might be easier:

- [ ] Space + Wheel to zoom (this is mostly important because zoom in/out on Chromebook is broken given that Alt is broken)
- [ ] Allow moving around hoving space down + click at any time. e.g. while dragging for example a crop corner one can hold space + click to move around and even zoom in/out
- [ ] Move around while dragging a handle and moving it near or outside of the visible image area
- [ ] Mouse middle to move around

**Comment by photopea** [comment]
1. Are you sure, that Alt + Wheel does not work on Chromebooks? I used to love Chromebooks, but after discovering the stubbornness of developers team, I think that Chromebooks are just a waste of a hardware. I hope this trend will pass, or something will replace them.
2. Space button already switches to a Hand tool (from any tool) ... is that what you mean?
3. "Active edges" would be a nice feature, but quite hard to make and I think that you can always do it by clicking twice.
4. What should be the mechanics of such "moving around"? I never used the middle mouse button.

**Comment by wernight** [comment]
1. I don't know about why it's not fixed, I imagine they have higher priorities or something about it being required for some compatibility or accessibility. In any case I love Chromebooks as they are cheap, easy to setup (wouldn't care if I lost one except for the price of buying one), secure, easy to maintain, new one running Android and working as tablets to better than tablets... I understand you may have felt frustration especially in early days. To answer your question, yes, it's still possible but freezes the Alt. It's like Alt works as a toggle and openes the context menu. So broken.
2. What I mean it:
     1. Zoom in
     1. Select crop tool
     1. Start cropping: Left click down and start dragging
     1. While doing so press space and drag, will start moving the canvas instead of resizing the drag rectangle
 3. If I remember some tools cannot work by clicking twice. Like the rectangle selection tool. May be open a seperate isssue as it's probably a harder one.
 4. Click and drag using middle button would be equivalent to Space + Left click.

**Comment by photopea** [comment]
2. It already works this way. Or are you trying it on a chromebook and you have discovered another CB-specific bug?
3. I made a new issue for this https://github.com/photopea/photopea/issues/160
4. I don't see many apps supporting this. I guess that most of users don't even know that a middle button exists. I think that Space + Left click is enough.

**Comment by wernight** [comment]
2. Looks like it's moving the selection rectangle instead of the whole canvas. What is it supposed to do? I don't have PS easily accessible and couldn't find a video showcasing this so may be people don't use it that much.
4. You're right it's less common especially on web. Desktop apps often support it but as you said, not that used.

Regarding (1) I found:

 - [ ] [Space + ctrl + drag](https://youtu.be/Vf5qsWO_1VM?t=57) didn't know that one, looks new and pretty cool to zoom in/out (not sure if webapp performance would allow this)
 - [ ] [Ctrl + Alt + Drag which I remember now using and was super useful](https://youtu.be/Vf5qsWO_1VM?t=182)

**Comment by photopea** [comment]
2. Yes, it moves the selection rectangle. It works the same as PS.

Space + Ctrl + drag already works. But zooming is not smooth ... since some users may not have WebGL, I decided to allwo zoom values only 1,2,3 ... or 1/2, 1/3, 1/4  (scaling pixels on the CPU is then faster).

Changing brush size with a preview would also be quite hard to do. Let's postpone it to the future.

**Comment by photopea** [comment]
It seems to me, that you just open Photoshop, open Photopea and write out all the differences that you find. I do realize, that there are thousands of differences.

I would be rather, if users reported me bugs, or some very important features, that they want to use on a daily basis.

**Comment by wernight** [comment]
I'll try Space+Ctrl on Chromebook. I think this would avoid the Alt issues.

**Comment by photopea** [comment]
- [Ctrl] + Space + Click Drag to zoom in/out and move around
- [ / ] and { / } to change brush size
- Hover over tools to see they shortcuts
All these should work already.

**Comment by wernight** [comment]
What I meant is like on most Google products: Take Inbox (or Gmail or Docs...) and press Shift + / (meaning `?`, but sometimes the shortcut is Ctrl + / or both). This will show a popup like:

![image](https://cloud.githubusercontent.com/assets/145667/24793996/567dca4c-1b84-11e7-9c20-1d05e086d7eb.png)

**Comment by photopea** [comment]
That is nice. Maybe it would be simpler to show a link to the official list of Photoshop shortcuts, what do you think?  We would not have to translate all of them (Photopea can now be switched to multiple languages using More - Language).

**Comment by wernight** [comment]
Either are fine. A menu entry pointing to a list is also good. I just think that most have a tooltip (X and D don't yet) and the most important would be IMO to list those that don't have one visible on the UI.

**Comment by photopea** [comment]
BTW. can you vote for Photopea here?  http://alternativeto.net/software/photopea/  ... to get 20th like? :)

**Comment by wernight** [comment]
Done.

**Comment by photopea** [comment]
I still see 19 :( you should confirm the email that they sent you.

**Comment by wernight** [comment]
Just had to update my account (didn't link properly so delete my Google account, recovered my old real account, linked correctly and voted again)

**Comment by wernight** [comment]
It's actually even making the news now: https://www.androidpolice.com/2021/06/09/google-continues-its-assault-on-the-chromebook-alt-key/

**Comment by photopea** [comment]
It is a real pitty, that because of this, Chrome OS is probably the worst environment for webapps.

**Comment by ashrafp216** [comment]
> 

Please add Font size increase and decrease shortcuts ( ctrl + shift + > and <), those are most used shortcuts

**Comment by photopea** [comment]
I have implemented these shortcuts.
