### ISSUE TITLE
Cannot drag and drop images to photopea

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#1548]
If I try to drag and drop images from other sites.
It will
1.) Duplicate current layer insted - if I drop to image area
or
2.) Does nothing and show error in console - if I drop to layers window
Uncaught SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at LG.Dz (pp.js:8052)

**Comment by Spastek** [comment]
I'm getting a similar issue when attempting to move text. I can move it view the arrow keys but if I drag and drop it will duplicate the text layer as a copy.

**Comment by Spastek** [comment]
I disabled all my add-ons for Firefox and this resolved the issue. Not sure which one was causing it.

**Comment by photopea** [comment]
Drag-and-dropping images from other tabs depends a lot on a browser. There was issue with Chrome, I think I fixed it.

Note, that if you drag an image, which is also a link, browsers just give Photopea that link. Photopea downloads a HTML file and tries to analyze it, to find image URLs. I.e. it may not work in 100% of cases.

**Comment by hxim** [comment]
Hello now it works when I drag drop from other tab but it still does not work for plugins as you describe here
https://www.photopea.com/api/plugins
> "Users can drag-and-drop images from your website to Photopea (as Photopea supports dropping images from any website, opened by a browser)."

![image](https://user-images.githubusercontent.com/6370548/61351651-cc529d00-a85a-11e9-9007-15f0b6782400.png)

**Comment by photopea** [comment]
Looks like it is a change in the behaviour of browsers. I will ask Chrome developers why did they change it. But it looks like they changed it for purpose, probably because of some security reasons.
