### ISSUE TITLE
wrap transformation glitch

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#1578]
I have encountered this before, but did not have the opportunity to record it.

I cannot reproduce it everytime, so i preferred to screen record it.

When trying to wrap transform a selection i get this glitch where the selction spands to the limits on the transformation square (if that makes sense). 

I can move it around, and when i apply the distorsion the size keeps the bigger form.

You can ESC and return to the normal size. 

Here is the video>
[Jul 24, 2019 11_08 PM.zip](https://github.com/photopea/photopea/files/3429614/Jul.24.2019.11_08.PM.zip)

**Comment by photopea** [comment]
Fixed! thank you Alvaro! :)

**Comment by avagp** [comment]
Thanks to you!

BTW I saw you presentation and I really laugh about the point you missed:
"chrome os is not that good"

XD
