### ISSUE TITLE
Magic Wand Select Not displaying properly

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#167]
I have been working all the weekend and i run into a graphical glitch that i have not encounter since months ago.

When using the magic wand to select, being on a certain zoom % different than 100%, i get the selection dotted lines all over the picture and i can not know where exactly is selecting. 
![screenshot 2017-04-17 at 10 08 04](https://cloud.githubusercontent.com/assets/11801254/25089832/675dc194-2356-11e7-91ca-ecf8eef8ea41.png)

Even though, all works as intended (you can paint the selected area, for instance).

BTW, add the shapes tool  🙏

**Comment by photopea** [comment]
I believe I have fixed it :) this error is present since the beginning, it happened to me several times, but I was too lazy to solve it.

**Comment by avagp** [comment]
I love your answers to the bugs XD

**Comment by avagp** [comment]
Still happends. But differently. Because the square selection is visible at the same time
![screenshot 2017-05-15 at 11 34 03](https://cloud.githubusercontent.com/assets/11801254/26065605/816c3544-3962-11e7-8ab7-a277f46c3480.png)

**Comment by photopea** [comment]
This is very strange. Can you send me your file and tell, where exactly did you click?

**Comment by avagp** [comment]
I can send you the file, i do not remember where i clicked.

I pasted a square selection of the amrs of my drawing. After i pasted it keep selected, but with this visual glitch. But as always, it was working ok despite of the glitch.
![monstruo](https://cloud.githubusercontent.com/assets/11801254/26067482/71e52800-3968-11e7-8552-d0980601ad02.png)

(i dont have a PSD i was working on a png, then saved)

**Comment by photopea** [comment]
I think it has something to do with the latest update of Chrome / Chrome OS ...  Also, the numbers on your ruler ar not sharp. Can you open the default pea.psd  and send me the screenshot right after opening it?

**Comment by avagp** [comment]
![screenshot 2017-05-15 at 12 26 28](https://cloud.githubusercontent.com/assets/11801254/26067946/bf500afa-3969-11e7-857e-3384d074c55a.png)
![screenshot 2017-05-15 at 12 25 56](https://cloud.githubusercontent.com/assets/11801254/26067947/bf51a662-3969-11e7-832e-46e744d0a9b7.png)

**Comment by avagp** [comment]
The default pea.psd dont have rulers, nor i can enable them

**Comment by avagp** [comment]
(also i am in beta channel of chrome os)  :/

**Comment by avagp** [comment]
btw, the rulers should have a line inside following the cursor, so i know where i am positioned all the time. (absolutly offside topic)

**Comment by photopea** [comment]
When you load Photopea.com, you see the quick menu at the center. There is Demo: pea.psd, so click on that pea.psd and then make a screenshot.

**Comment by avagp** [comment]
![screenshot 2017-05-15 at 12 36 17](https://cloud.githubusercontent.com/assets/11801254/26068325/21cc9076-396b-11e7-8b76-d83fa190e9ce.png)

**Comment by photopea** [comment]
That is what I thought. The project should be 512 pixels wide, but it is 640 pixels wide on your screenshot ... i.e. rulers don't show actual pixels.

**Comment by avagp** [comment]
Here is with the dafault resolkution of the chromebook (1920x1080 which i do not use)
![screenshot 2017-05-15 at 12 38 29](https://cloud.githubusercontent.com/assets/11801254/26068423/6bd52926-396b-11e7-83e5-69f39086945e.png)

I use 1536x864

**Comment by photopea** [comment]
But your screenshot is always 1920x1080 px ... it is quite strange.

**Comment by photopea** [comment]
Ok, I am very sorry. It was not related to any Chrome update. It was my own mistake. It is fixed now.

**Comment by avagp** [comment]
Please do not apologize.

You doing a great job on the support​!

But remember, not every problem is because of chrome :P

Le 15 mai 2017 1:17 PM, "Photopea" <notifications@github.com> a écrit :

Ok, I am very sorry. It was not related to any Chrome update. It was my own
mistake. It is fixed now.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/photopea/photopea/issues/167#issuecomment-301541594>,
or mute the thread

**Comment by avagp** [comment]
Sorry to bother you again, but. I used "select all" and...
![screenshot 2017-05-20 at 20 11 58](https://cloud.githubusercontent.com/assets/11801254/26280239/e15e6f82-3d98-11e7-877d-dd2afd10bc83.png)

**Comment by avagp** [comment]
Here is a video: https://drive.google.com/file/d/0BxACIQ9JCuosXzBfZHltTDBMdk0/view

When selecting the selection is abruptly displaced.

Also look the miniature of the layer. Is completely distorsioned.

**Comment by photopea** [comment]
This bug was never speicific for the Wand Tool. It caused all selections to be rendered incorrectly.

Sadly, I can not reproduce it :( Have you tried to reproduce it on some other computer? What about anonymous mode? Can you send me your picture?

**Comment by avagp** [comment]
I would try. But is furtive.

**Comment by photopea** [comment]
Any news? Did you try the anonymous mode?

**Comment by avagp** [comment]
Yes, but i cannot​see any differences. When something weird happens I will
change to incognito.

**Comment by photopea** [comment]
Ok, I finally managed to reproduce it. It happens only with a specific window size (it may be ok if you resize the window). I will try to fix it soon.

**Comment by photopea** [comment]
It should be fixed now.
