### ISSUE TITLE
Font with emoji symbols

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2105]
I tried to use font with emoji symbols like this one
https://www.google.com/get/noto/#emoji-zsye
but after I copy and paste some emoji there (for example this one https://emojipedia.org/automobile/)
it automatically changes font to DejaVu Sans and shows only two rectangles. I can change it back to Noto Emoji font and it shows correct emoji symbol instead of first rectangle but it still appends second rectangle symbol that cannot be removed (see screenshot)
![image](https://user-images.githubusercontent.com/6370548/80862905-d83c0e00-8c78-11ea-94ce-a6c24609cfde.png)

**Comment by photopea** [comment]
Hi, there was a bug, when Photopea can not detect, that the font supports the car emoji. It is fixed now. If you paste an emoji into a text with a correct font, the font will not be changed to DejaVu Sans.

Also, when you paste an emoji, only one character (one emoji or one square) should appear. I think in your case, you copy-pasted an emoji with a space character, which is not supported by the emoji font (rendered as a square).

**Comment by hxim** [comment]
@photopea 

> Also, when you paste an emoji, only one character (one emoji or one square) should appear. I think in your case, you copy-pasted an emoji with a space character, which is not supported by the emoji font (rendered as a square).

No I copy-pasted only one emoji character (no space character) and it is still showing square in the end :(
See this video: https://youtu.be/bFMWT7wZcWc
I pressed only CTRL+V

**Comment by photopea** [comment]
Thanks, it should be fixed now.

**Comment by hxim** [comment]
@photopea 

Hello I found 2 more issues: 
(after you load Noto Emoji font above)

1.)
When I select with Type Tool for example strawberry emoji here
https://www.photopea.com/#iUq9d1Afj
and click on some glyph (number zero for example) to replace it it will add unwanted square after inserted glyph/symbol.

2.)
When I go with Type Tool cursor to the end (after last character) and try to delete emojis with Backspace key on keyboard it does not work (doing nothing).

**Comment by photopea** [comment]
Hi, it should be fixed now, thanks! :)

**Comment by lkorczowski** [comment]
Sorry but I still cannot display emoji. I tried copy-pasting emojipedia or using macos native emoji, trying all kind of different font and still.. a beautiful rectangle instead.

![Screenshot 2021-10-21 at 21 54 39](https://user-images.githubusercontent.com/15196605/138347815-4e9254ea-91b1-4b31-a4f0-d0db7ab529c1.png)
.
