### ISSUE TITLE
Selection or shape from work path

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2123]
I want to make selection from this path (to fill it and convert to actual shape layer) but it keeps selecting only rectangle around it not the actual path.

See the psd file here:
https://www.photopea.com/#i3-nifsBN

It is doing this when I go to Paths window and clicking Selection button or doing CTRL+ENTER :
![image](https://user-images.githubusercontent.com/6370548/81282905-1ad85e80-905c-11ea-99b5-b8703f2ea5ca.png)

**Comment by photopea** [comment]
Hi, I guess you made this path from a selection. There was an error in our procedure, which converted selection to a path.

I fixed it. Now, when you convert a selection to a path, a new path should be selectable correctly. But your PSD will not work, since the path in it is corrupted.

**Comment by hxim** [comment]
Yes, I created it from selection but I just tried it again and it is still not working for me:
![image](https://user-images.githubusercontent.com/6370548/81289561-e918c500-9066-11ea-9e78-fac233597179.png)

**Comment by photopea** [comment]
sorry, now it is fixed.
