### ISSUE TITLE
Loads files wrong

### ISSUE THREAD

**Issue by ReeceBar** [photopea/photopea#2152]
Photopea used to load DDS files perfectly fine, now it misses up the colors making DDS files look horrid.

**Comment by photopea** [comment]
Hi, I can still open DDS files in Photopea. Could you share your DDS files with us?

**Comment by ReeceBar** [comment]
Okay, so when I tried to send the examples, I got a message too large
thing, do you know of a workaround?

**Comment by photopea** [comment]
Can you send me just one file instad of all?

**Comment by ReeceBar** [comment]
Alright Well, the original was 16MB, and when I exported it from Photopea
it became 2.66MB

**Comment by photopea** [comment]
Photopea uses compression when exporting DDS.

**Comment by photopea** [comment]
I will close it now, but we can keep discussing it. I am 99.9% sure, that Photopea has been treating DDS files the same way for the past 3 years (we did not change anything).

Please, specify, what the problem is, and for what images it happens.

**Comment by ReeceBar** [comment]
It breaks the DDS file, I'm pretty sure the compression is probably the
issue, since it can somehow make the file from 16MB and make it 2.66MB, but
it breaks the file.

**Comment by ReeceBar** [comment]
Here is another example The 'Copy' is the one I simply the other file but
exported from Photopea. See how it missed it all up?

**Comment by photopea** [comment]
Hi, I do not see any files in your response. Please, respond in a browser at  https://github.com/photopea/photopea/issues/2152

**Comment by ReeceBar** [comment]
Okay here's a link to my google drive with the other example, the 'copy' is just the one I put into photopea and exported, see how it's completely different/missed up? https://drive.google.com/open?id=1xTksUjhjz5bI9PH7K0BLXZ69w6XECt2L

**Comment by photopea** [comment]
Hi, there really was a bug. I fixed it. Your DDS file should work well in Photopea now.

Please, send me more such files, if they work wrong in Photopea.

**Comment by ReeceBar** [comment]
Well, yeah there was a bug, hence why I started this conversation.. thanks,
although the shack dds works now, the vaultsuit still gets messed up. I
have updated the drive with the other issue
https://drive.google.com/drive/folders/1xTksUjhjz5bI9PH7K0BLXZ69w6XECt2L?usp=sharing

**Comment by photopea** [comment]
What exactly is the problem in this case? I see, that the DDS gets smaller, after you re-export it through Photopea.

But what is wrong? Does the game not accept the new DDS? Or the colors are different?

**Comment by ReeceBar** [comment]
The colors ingame are what its supposed to be, the dds that gets smaller
completely messed it up making the blue part yellow, and the yellow trim
blue somehow.

**Comment by photopea** [comment]
So you loaded the DDS from Photopea into your game and the colors of the texture in a game changed? Could you show me a screenshot? Or where exactly do you see the blue turn into yellow?

**Comment by Travisko** [comment]
I have a similar issue.
This is what it looks like in game:
![SSingame](https://user-images.githubusercontent.com/8236255/83076952-7dfa5700-a044-11ea-96ed-1d58afaa9a10.png)
This is what it looks like once opened in Photopea:
![SSphotopea](https://user-images.githubusercontent.com/8236255/83076969-82bf0b00-a044-11ea-8c1e-ed3ad63680e3.png)
The file itself:
[advanced_spiritualist_city_l04.zip](https://github.com/photopea/photopea/files/4692104/advanced_spiritualist_city_l04.zip)

**Comment by photopea** [comment]
Seems like the red and blue channels are swapped. I will look into it.

**Comment by photopea** [comment]
It is fixed now. Thanks for reporting it :)  If you find any other problems, let us know!

**Comment by photopea** [comment]
BTW. with a PNG format, your DDS (345 kB, 107 kB zipped) could be 16x smaller (21 kB). That is why I used PNG and JPG in all my games in the past :)

![advanced_spiritualist_city_l04](https://user-images.githubusercontent.com/15955558/83250350-46a4bb00-a1a8-11ea-8243-3727a15691c3.png)

**Comment by ReeceBar** [comment]
Okay, but games that dont use those, like fallout, won't work with those
files.

**Comment by photopea** [comment]
I see, you are replacing textures in an existing game. I thought you are making your own game.

**Comment by ReeceBar** [comment]
Although I do have something planned, yes I wanted to replace textures in
an existing game.
