### ISSUE TITLE
Unable to import alpha channels

### ISSUE THREAD

**Issue by JirkaVasica** [photopea/photopea#2238]
Hi,

we are working with RGBA textures for specularity in PBR rendering (RGB - specular, A - smoothness). Compared to photoshop, photopea doesn't import the texture as RGB + alpha channel, but converts the image to RGB. This applies to all the formats (.psd, .tiff, .tga, .png). 

![Example](https://user-images.githubusercontent.com/48250404/84993925-3601b800-b14a-11ea-8f35-812fe4597895.png)

**Comment by photopea** [comment]
Hi, can you share such PSD with me, so that I can see, what is the difference between Photoshop and Photopea?

**Comment by JirkaVasica** [comment]
While preparing that .psd file I have noticed that .psd loaded correctly. After trying all the formats I might have missed it. However other formats like .tif or .png are unable to load the alpha channels separately. Nevertheless the .psd is not flawless. Even though it loads the .psd file correctly, re-saving it with photopea brokes the file and other softwares sees the alpha channel as plain white channel (same results after saving it as .png, .tif, .tga).

Here are the files (.psd and .tif), which were created using photoshop: [Floor_tiles_4.zip](https://github.com/photopea/photopea/files/4798170/Floor_tiles_4.zip)

Example of alpha channels differences after saving:

![diff](https://user-images.githubusercontent.com/48250404/85015092-aec33d00-b167-11ea-9682-4646c6e6d4f8.png)

**Comment by photopea** [comment]
Hi, I am very confused by you. You are mentioning too many things. Let's solve problems one by one.

I opened your PSD in Photopea, the structure is the same as when opened in Photoshop. Then I saved it as a new PSD, and opened it in Photopea. The structure was the same as if I open your original PSD in Photoshop (I do not see any differences). So what is the problem with a PSD?

**Comment by JirkaVasica** [comment]
- Photopea open RGBA .psd saved in photoshop ✅
- Photopea open RGBA .psd saved in photopea ✅
- Other programs open RGBA .psd saved in photoshop ✅
- Other programs open RGBA .psd saved in photopea ❌ -> alpha channel is white
- Photopea open RGBA .tif, .png, .tga ❌-> RGBA is converted to RGB

**Comment by photopea** [comment]
Ok, let's look at the problem with a white alpha channel.

What "other program" do you use to open a PSD? Are we talking about the PSD which you sent me, which was later opened in Photopea and exported as a new PSD?

**Comment by photopea** [comment]
I would like to reproduce the issue myself.

**Comment by JirkaVasica** [comment]
For example Unity (game engine)

**Comment by photopea** [comment]
It is hard for me to believe. Are you sure you did not mix something up?

If two PSD files look identical in Photoshop, they should work similarly in other programs (even if one was made by Photoshop and another by Photopea).

**Comment by JirkaVasica** [comment]
Not that I know of. Here is the video showcasing the use case:

https://www.youtube.com/watch?v=R5GUXlegewY&feature=youtu.be

**Comment by photopea** [comment]
I understand it now. The PSD from Photopea had a bit different structure, even though the "meaning" was the same.

I fixed it. Please, let me know if the PSD from Photopea works the same as the one from Photoshop.

**Comment by photopea** [comment]
Could you try it? I think the PSD should work well now. Could you describe the problem with TGA, please?

**Comment by JirkaVasica** [comment]
It works except one use case. In the example .psd file there are two layers Spec (original layer) and the other one is plain white layer. Adding new layers on top, editing channels etc. works great. All the changes are now translated properly to RGBA format. However for some reason deleting the first layer at the bottom results in the same error as before the changes (RGB - correct, A - white only).

**Comment by photopea** [comment]
That problem would happen in Unity, if you deleted the white layer in Photoshop, and saved a PSD from Photoshop. It is not related to Photopea at all. It can only be fixed by Unity in their PSD handler.

A PSD file contains a list of channels at the end. Channels are like this:

  R, G, B, Transparency, C0, C1, C2, C3 ...

Transparency is present only if it is not fully opaque (255). C0, C1, C2 ... are channels in a Channels window (if there are any).

Unity reads the first four channels of these. If you delete the white layer (in Photopea or Photoshop),  Transparency is not fully 255, so it is present in that list, and Unity reads Transparency instead of C0.

**Comment by JirkaVasica** [comment]
Oh I see, thanks for clarification 👍 

Regarding .tga and other formats (.png, .tif...) which are saved in RGBA format. Here is video showcasing how photopea converts them to RGB format after import:

https://www.youtube.com/watch?v=4On4_I_Ow0c&feature=youtu.be

**Comment by photopea** [comment]
Could you send me that PSD? Is it opened differently in Photoshop than in Photopea?

**Comment by JirkaVasica** [comment]
In photoshop this seems to be problem too :/ We have switched from .tiff and .tga to .png with RGBA textures only few days ago so we are still analyzing the proper import/export workflow with .png formats, but it would be great to have option to extract transparency to separate channel on import in photopea. Nevertheless importing .tiff worked in photoshop, I will send you example texture once I get to the different computer.

Don't know if this is a new bug or it was there before, but after upscaling imported .psd (e.g. Floor_tiles_4.psd in the zip above) content of the alpha channel is not upscaled:

![scale_issue](https://user-images.githubusercontent.com/48250404/85402479-0ee92300-b55c-11ea-88d8-1629aae03ba6.JPG)

**Comment by photopea** [comment]
I fixed it. Image - Image Size will resize the Channels, too, now.

Regarding the file format: if you want to save a channel, which is not RGB and not a transparency, store it in a separate file (e.g. grayscale PNG). Most of image editors interpret the fourth channel as a transparency, so you will not be able to work with it comfortably.

**Comment by photopea** [comment]
So as it seems, TGA files can not have transparency information. They can have a fourth channel, which is treated as an independent channel (and not transparency).

I fixed the TGA opening: a fourth channel is added to Channels of a document. During the export, a first channel in Channels is saved as a fourth channel in a TGA file.

So now, Photopea should open all files the same way as Photoshop does. If you still find any differences, please, let me know.

**Comment by eddieataberk** [comment]
> So as it seems, TGA files can not have transparency information. They can have a fourth channel, which is treated as an independent channel (and not transparency).
> 
> I fixed the TGA opening: a fourth channel is added to Channels of a document. During the export, a first channel in Channels is saved as a fourth channel in a TGA file.
> 
> So now, Photopea should open all files the same way as Photoshop does. If you still find any differences, please, let me know.

Still having problem with .tif files. It multiplies the alpha and gives transparent rgb channels.

<img width="255" height="171" alt="Image" src="https://github.com/user-attachments/assets/f347efff-29c3-44c5-bc0c-a13ce31a562d" />

however altough alpha channel is empty there is data on rgb channels which can be accessed with Gimp or Adobe products but not with photopea

**Comment by photopea** [comment]
I think Photopea should treat every file the same as Adobe Photoshop.

If you are saying that it is not so, please, provide some proof, e.g. a TIFF file.

**Comment by eddieataberk** [comment]
> I think Photopea should treat every file the same as Adobe Photoshop.
> 
> If you are saying that it is not so, please, provide some proof, e.g. a TIFF file.

I don't have Photoshop installed but i am assuming it is same Gimp and Substance

Channels in Gimp

<img width="358" height="146" alt="Image" src="https://github.com/user-attachments/assets/d0cf000d-57b1-450a-85b0-19352a2531c6" />

Channels in Photopea

<img width="250" height="168" alt="Image" src="https://github.com/user-attachments/assets/8962facf-36bf-47e0-8935-7799a9615710" />

[tiftest.zip](https://github.com/user-attachments/files/21576508/tiftest.zip)

**Comment by photopea** [comment]
Okay, I have fixed it. Photopea should detect that the fourth channel is not a transparency channel in TIFF files such as this one.
