### ISSUE TITLE
Stroke of the shape - wrong corners rendering

### ISSUE THREAD

**Issue by avagp** [photopea/photopea#2260]
Hi, i am reposting this issue, because the original one has been unasigned from 6 months now.

The original Issue is the #1856, and still happens

The reporter there have a excelent gif.

I can give you the PSD i am working on, if you please
[Logo Altiro.zip](https://github.com/photopea/photopea/files/4821090/Logo.Altiro.zip)

**Comment by photopea** [comment]
Fixed! Thanks! :)

**Comment by avagp** [comment]
I still get ir :/
[27db6fece0af695bc8cae3fc97684110.zip](https://github.com/photopea/photopea/files/4828557/27db6fece0af695bc8cae3fc97684110.zip)

**Comment by photopea** [comment]
Where exactly do you see it in your document? I can not see it.

**Comment by avagp** [comment]
Here:
https://video.drift.com/v/abHcYvLmq4G/

**Comment by photopea** [comment]
Hi, I can not play the video at your link. Could you maybe send it to me to support@photopea.com ?

**Comment by avagp** [comment]
I uploaded the video here
[DRIFT-VIDEO-1455130-1506513-1593116482934-1.zip](https://github.com/photopea/photopea/files/4833660/DRIFT-VIDEO-1455130-1506513-1593116482934-1.zip)

**Comment by photopea** [comment]
Hi Alvaro. In this case, you probably do not understand how vector graphics work. I wrote a description of vector graphics here: https://www.photopea.com/learn/vg-structure

In your case, the knot is not sharp, because its two handles are in one line with the main anchor. So the corner style settings do not apply to it, as there is no corner in it. You should double-click the knot to allow anchors move freely.


![image](https://user-images.githubusercontent.com/15955558/85792776-575b3900-b734-11ea-87e8-bd69f0b8ed7f.jpg)

**Comment by avagp** [comment]
Oh, my bad!

Thanks for clarifying!

:D
