### ISSUE TITLE
Live Messaging examples not working

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2281]
JSFiddle examples from here
https://www.photopea.com/api/live

- Demo: Wait for "done", then send a script
- Demo: Load a file (as ArrayBuffer) and give it to Photopea

are not working for me and there is this error in console window:

```
pp.js:10 Uncaught (in promise) DOMException: Failed to execute 'getLayoutMap' on 'Keyboard': getLayoutMap() must be called from a top-level browsing context.
    at k.Dc (https://www.photopea.com/code/pp.js:10:8)
    at new k (https://www.photopea.com/code/pp.js:9:65)
    at new dd (https://www.photopea.com/code/pp.js:10388:48)
    at window.onload (https://www.photopea.com/code/pp.js:10823:32)
```

**Comment by photopea** [comment]
Hi, yes, that is correct. The problem is, that JSFiddle started to use sandboxed iframes, which do not support web messaging by default.

Could you recreate these demos at www.glitch.me ? I would replace the links with links to your demos at glitch.me

**Comment by hxim** [comment]
Hi I attempted to do so here for this demo https://jsfiddle.net/msab5vk1/ (Demo: Load a file (as ArrayBuffer) and give it to Photopea):
https://photopea-demo-1.glitch.me/
but it is still showing same error and not working in Google Chrome browser most of the time:
![obrazek](https://user-images.githubusercontent.com/6370548/86768886-8768dd00-c04e-11ea-8577-4d7ad83e4aa2.png)
In firefox it seems to work in this case.

**Comment by photopea** [comment]
Hi, I fixed the error with getLayoutMap(), does it work well now?

**Comment by hxim** [comment]
Hi, unfortunately it does not.
Error is away but in Chrome it still does not load image from arraybuffer for me as it should see screenshots:
Firefox: (ok)
![obrazek](https://user-images.githubusercontent.com/6370548/86772728-dca7ed00-c054-11ea-93fa-a0c0c39cde6d.png)
Chrome: (not working)
![obrazek](https://user-images.githubusercontent.com/6370548/86772736-e0d40a80-c054-11ea-8330-6797a365726a.png)

**Comment by photopea** [comment]
It opens in Chrome too, once in a while.

The problem is, that there are three Message Events in Chrome, but four in Firefox.

**Comment by photopea** [comment]
Can you try to put your Javascript code directly into a HTML page? I think one browser loads and runs your JS file before loading the iframe, while another browser does the opposite.

**Comment by hxim** [comment]
OK. I also put window.addEventListener to onload of iframe and it is working now in both browsers.
`onload="iframeLoaded(this)" `

Also I had to add
`if (e.data == "done")`
so it ignores this additional message appearing in firefox before first "done" message
![obrazek](https://user-images.githubusercontent.com/6370548/86883048-8d63ca00-c0f1-11ea-861d-b42e433ad255.png)

And replaced this non-existing image used in first demo with image from second demo
https://www.photopea.com/api/img/pug.png

Code:
https://glitch.com/edit/#!/photopea-api-demo
Demos:
https://photopea-api-demo.glitch.me/

**Comment by photopea** [comment]
Great, I put a link to your demos to www.Photopea.com/api/live
