### ISSUE TITLE
Says that ads are blocked but they aren't

### ISSUE THREAD

**Issue by Romarain** [photopea/photopea#2325]
Hello,
I have a popup opening every minutes or thirty seconds saying :
![2020-07-24_16h45m40s_chrome](https://user-images.githubusercontent.com/22033256/88404950-dfce0780-cdce-11ea-8ed3-bbaed56cc4c7.jpg)

This is not true, given that I've been in every section and sub-sections of the settings, in order to allow all kind of things 👍 
![2020-07-24_16h59m04s_](https://user-images.githubusercontent.com/22033256/88405086-0f7d0f80-cdcf-11ea-9b60-ef24e1dd8f8f.jpg)
![2020-07-24_16h59m11s_](https://user-images.githubusercontent.com/22033256/88405095-12780000-cdcf-11ea-98ad-50bb16b02a6b.jpg)
![2020-07-24_16h59m23s_chrome](https://user-images.githubusercontent.com/22033256/88405106-16a41d80-cdcf-11ea-925e-e294779b816a.jpg)
![2020-07-24_16h59m28s_chrome](https://user-images.githubusercontent.com/22033256/88405116-199f0e00-cdcf-11ea-899e-fb05a48829ce.jpg)

**Comment by photopea** [comment]
Hi, so do you see ads in Photopea without any problems?

I think your browser extensions could be blocking ads. Can you try Photopea in Incognito mode, where all extensions are disabled?

**Comment by 253488655422** [comment]
I'm going crazy with this stupid glitch can you fix yes there are no ads but I already tried ingontio mode and no extensions just please fix this amazing site every 30 sec I see this when I'm editing a psd and it always distracts me. I found a temp workaround but recently the alert control extension which blocked this bug doesn't allow me to open/edit psds it says browser modifying code. I don't have any third party ad blockers if you  are wondering or proxys/vpn or whatever just FIX IT!!! (This glitch has been here for months and I'm not joking) and It's not my internet I already tried switching it's not the ISSUE. Ok anyways thank you for the person who opened this issue. I really love photopea but I hope you improve it :)

**Comment by photopea** [comment]
@253488655422 Let me help you find out what exactly is blocking your ads :)

What web browser are you using? Have you tried a different browser?

What number do you see at the end of the message about ad blocking? Is it zero?

**Comment by 253488655422** [comment]
I use Google Chrome and use I have tried Microsoft Edge and Opera and it's 0

**Comment by 253488655422** [comment]
I know this is off-topic but how do I get perspective warp? Can anyone tell me.

**Comment by photopea** [comment]
Can you open or download this file from your browser? https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js

Perspective transform is described here: https://www.photopea.com/learn/free-transform

**Comment by 253488655422** [comment]
Sorry I was eating oh I couldn't open that page and thanks I figured out perspective warp

**Comment by photopea** [comment]
Then, ask your internet provider, why is he blocking that page. That page is crucial for the correct functionality of ads in Photopea.

Maybe some programs in your computer are blocking it,, it is hard to tell.

**Comment by photopea** [comment]
Then, ask your internet provider, why is he blocking that page. That page is crucial for the correct functionality of ads in Photopea.

Maybe some programs in your computer are blocking it,, it is hard to tell.

**Comment by 253488655422** [comment]
Uh huh my ISP doesn't block webpages isn't there any way I can access it (also I have access to my lan webpage and that page is not blocked also what programs should I check for that is blocking it.

**Comment by 253488655422** [comment]
I didn't seem to have this problem yesterday though.

**Comment by photopea** [comment]
Just find a way to open the URL  https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js . Try different browsers or disable some extensions. Can you open it in Incognito mode?

**Comment by 253488655422** [comment]
It didn't work in Ingontio mode or microsoft edge.

**Comment by photopea** [comment]
I recommend you to take you computer to a repair shop, so that they find
out what is blocking it.

That URL is a regular URL, which should be openable on any device connected
to the internet.

**Comment by 253488655422** [comment]
Then why do other people have this problem

**Comment by photopea** [comment]
I think that URL was blocked by browser extensions in cases of other
people. We will never know, because they don't reply.

**Comment by Romarain** [comment]
> Hi, so do you see ads in Photopea without any problems?
> 
> I think your browser extensions could be blocking ads. Can you try Photopea in Incognito mode, where all extensions are disabled?

Sorry, I forgot to mention that I have no adblock-like extension installed; I won't try incognito since there is no extension to block ads installed ;)

**Comment by 253488655422** [comment]
I don't see ads already tried Incognito mode did'n't work

**Comment by photopea** [comment]
If you do not cooperate, there is no way I can help you :(

**Comment by Romarain** [comment]
@photopea 

> If you do not cooperate, there is no way I can help you :(

You don't cooperate neither : somebody explained that he tried incognito mode, and it didn't fix the problem. So please listen to him, and don't ignore him so you can say me "you don't cooperate"..

This being said, I think I found a possible track : I use HTOSMAN, a software to udpate my HOST file in order to set a blacklist of domains, for security purpose (anti-malware technic).

I've just checked, and _pagead2.googlesyndication.com_ is one of the domains blocked : 

![2020-07-24_19h31m02s_sublime_text](https://user-images.githubusercontent.com/22033256/88418797-63462380-cde4-11ea-9766-91fd570ae897.jpg)

But the thing is disabling it doesn't seem to fix anything. Note that commentating a line in the HOSt file is **immediatly** taken into account by any software trying to reach an URL.

**Comment by photopea** [comment]
I really don't know much about these domain blacklisting programs :(  I am afraid I can not help you with it :( Maybe you should ask authors of HTOSMAN about this issue?

I guess you have problems with ads not only in Photopea, but in other websites, too. So the problem is not related to Photopea, you need to fix displaying of ads on the web in general.

**Comment by Romarain** [comment]
> I guess you have problems with ads not only in Photopea, but in other websites, too.

I don't really know. There's not much of the websites I go onto with trash-ads in sidebars anymore. 

> you need to fix displaying of ads on the web in general

I don't want that. It's a security breach (at least the backlists I use considere them as potential malware vectors).

I found a **workaround** !

1. I disabled all the entries of my blacklist to test if it was the source of the problem : and indeed, Photopea ads reappeared !
2. Then, I re-enabled all the lines, and manually disabled a few "google" entries. It seems to have no effect and the ads were still appearing.
3. So, I re-enabled all, and ads are still there in Photopea ! :)

So maybe the **cookies** of something similar keep the connection **_alive_** with those ads, and it works.

**Comment by Romarain** [comment]
I think you may close this issue, because it was specifically linked to my configuration. I'm gonna summurize the workaround in the original post.

**Comment by photopea** [comment]
As there are millions of people who use Photopea, there are at least hundreds who use domain-blocking software as you do, without even knowing about it. So I think this issue can be useful to many people.

**Comment by Romarain** [comment]
You're right, and I'm glad to have possibly helped people using this great software that you created.
I benefit from this thread to say a big THANK YOU for removing me the pain to use obscure Photoshop versions, you can't even know how Photopea was a relief for me. :) As soon as I can afford it, I will subscribe to a year plan. Cheers !

**Comment by 253488655422** [comment]
It says solved how do I fix it then?

**Comment by photopea** [comment]
@253488655422 You probably have some program in your computer, which blocks https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js  , or your internet provider is blocking it (ask him about it).

**Comment by 253488655422** [comment]
I still don't understand why is my computer blocking that link and if it has caused problems in the past have you ever moved the link to something that won't cause bugs/issues? I'm asking because I tried almost everything you told me.

**Comment by photopea** [comment]
@253488655422 Have you asked your internet provider about it?

We did not require users to view ads in the past, we enabled it recently (that is why you could get away with hiding ads a week ago).

**Comment by 253488655422** [comment]
I'm not requesting you to remove ads I honestly don't care about ads anything is better than that stupid alert dialog that keeps spamming my screen and making me frustrated. I'm telling you is there any way you can change the ad link to something that won't get blocked by my computer or other people who might have this problem.

**Comment by photopea** [comment]
@253488655422 We did not make your computer like this (so that it blocks ads), you did it, or your internet provider did.

As you refuse to get in touch with your interent provider, or investigate it yourself, I guess you will have to buy a new computer, or someow find 3 USD per month, so that you can afford a Premium account.

**Comment by 253488655422** [comment]
I FIXED IT!!! I MOVED THE WINDOWS HOST FILE TO SOMEWHERE ELSE AND IT UNBLOCKED THE ADS!!!!
anyone who has this problem go to C:\Windows\System32\drivers\etc find the host file move it if you don't want to delete it and it fixes it thanks @Romarain

**Comment by photopea** [comment]
@253488655422 But we still don't know who modified your host file this way :( There should not be any domains blocked, when you install Windows.

**Comment by 253488655422** [comment]
I think I know why I just noticed as soon as I did this my youtube ad blocker stopped working is it possible this is what messed with my host file?

**Comment by Romarain** [comment]
@253488655422 For Christ's sake, don't delete nor move this file, it's essential for Windows to manage domains access.
Just comment lines you want to disable in it, by adding a "#" in front.

**Comment by 253488655422** [comment]
I didn't delete it I just moved it to a different folder @253488655422  I tried to do that but it didn't work.
