### ISSUE TITLE
Problem with opening PDF exported from Autocad

### ISSUE THREAD

**Issue by Shovaln** [photopea/photopea#2407]
Hi,

Unfortunately the Editor does not open my PDF file.
I tried saving it in various protocols.

It's the first time I'm having difficulties in opening a pdf exported this way - been opening dozens of PDF files so far :)

Thanks you,
NS
[016 02.09.20-1.pdf](https://github.com/photopea/photopea/files/5160935/016.02.09.20-1.pdf)

**Comment by photopea** [comment]
Hi, I fixed the problem, it should work well now. Thanks for reporting it! :)

**Comment by Shovaln** [comment]
Hi,
Unfortunately it still doesn't work :(


[image: www.shovaln.com] <http://www.shovaln.com>
  +972 52 3411668 shovaln@gmail.com
       .Tel Aviv, 8 Rothschild Blvd
              www.shovaln.com






‫בתאריך יום ד׳, 2 בספט׳ 2020 ב-17:28 מאת ‪Photopea‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by Shovaln** [comment]
OK now it works!
thank you so much :)

NS
[image: www.shovaln.com] <http://www.shovaln.com>
  +972 52 3411668 shovaln@gmail.com
       .Tel Aviv, 8 Rothschild Blvd
              www.shovaln.com






‫בתאריך יום ד׳, 2 בספט׳ 2020 ב-18:08 מאת ‪Nadav Shoval Architect‬‏ <‪
shovaln@gmail.com‬‏>:‬
