### ISSUE TITLE
Error after Path - Make Selection

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#2469]
1. Open new project
2. Create one shape layer with two rectangles (using Rectangle tool with Shape and Path setting)
3. Select Path Select tool
4. Select one of the rectangles with Path Select tool
5. Right click mouse and select Make Selection
6. Click "OK" with mouse
7. Click down arrow (down triangle button) in top toolbar
8. Error appears as seen on screenshot and I cannot select shapes with Path Select tool (not working)
![image](https://user-images.githubusercontent.com/6370548/93985010-c9b7d580-fd84-11ea-9948-450c467794ce.png)

**Comment by photopea** [comment]
fixed, thanks! :)

**Comment by dentistformyeye** [comment]
I'm still unable to use Path Select or Direct Select (and the blue outline disappears) after using "Make Selection" on a shape layer. Clicking a different layer and clicking back to the shape layer resolves this.
1. Draw a small rectangle using the Rectangle tool on the Shape setting.
2. Right-click and click "Make Selection."
3. Deselect using control-D or Select > Deselect.
4. Attempt to use Direct Select or Path Select.
![image](https://user-images.githubusercontent.com/51429646/94377171-521fd880-00ed-11eb-8dab-cb4eb1d8fc19.png)

**Comment by photopea** [comment]
@dentistformyeye Hi, that is on purpose. You can go to a Paths panel and "activate" the shape path again by clicking it.
