### ISSUE TITLE
USER INTERFACE has problem

### ISSUE THREAD

**Issue by awrawfaef** [photopea/photopea#2493]
Whenever I type or edit text user interface is having trouble.
![Screenshot 2020-10-01 at 9 53 15 PM](https://user-images.githubusercontent.com/72209727/94819126-7a7f3e00-0431-11eb-8538-4241bd2605fc.png)

**Comment by photopea** [comment]
Hi, what exactly is the problem? Why do you have so large grey are on the right side?

**Comment by awrawfaef** [comment]
whenever I try to edit the text color white gray on the right side appears. I try to create new file but it's the same problem. It will come back only when I click on the other layers

**Comment by photopea** [comment]
Can you disable all browser extensions? Or try if it happens in Incognito Mode?

**Comment by 4rEnd3r** [comment]
I have the same problem. When I type text, the gray bar gets larger as I'm typing and it's hard access the left side of the editor. II have tried it in an incognito window and it still happened.

**Comment by photopea** [comment]
@4rEnd3r Does it happen even in Incognito Mode?

**Comment by 4rEnd3r** [comment]
Yes, it still happens in Incognito Mode.

**Comment by photopea** [comment]
What browser do you use? Can you try to update it?

**Comment by awrawfaef** [comment]
how to update? i was just using web tool

**Comment by photopea** [comment]
what web browser do you use?

**Comment by awrawfaef** [comment]
Chrome

**Comment by photopea** [comment]
What version of Chrome do yo use?

**Comment by photopea** [comment]
It should be fixed now. Does it work better?

**Comment by awrawfaef** [comment]
It's still like this. I don't know what seems to be the problem when editing texts the large gray part still appears.

![Screenshot 2020-10-02 at 5 15 30 PM](https://user-images.githubusercontent.com/72209727/94907537-e82f7680-04d2-11eb-9939-05c5e27655c5.png)

**Comment by photopea** [comment]
Can you close Photopea and open it again? Does it still happen?

**Comment by awrawfaef** [comment]
Yes I even restart my laptop

**Comment by mustafaGFX** [comment]
hi guys
try to install photopea  by clicking > more > install photopea

**Comment by photopea** [comment]
@awrawfaef Can you send me your PSD to support@photopea.com and describe, where exactly did you type, to make the photopea window shift to the right?

**Comment by photopea** [comment]
I believe it has been fixed.
