### ISSUE TITLE
Unable to save as PSD or converted files are unable to open

### ISSUE THREAD

**Issue by yijuchoo** [photopea/photopea#2552]
Tried to save Figma & Sketch files as PSD but unable to. Upon clicking Save as PSD button, page hangs there and nothing happen. Exported SVG file is unable to open in Illustrator. The filsize I'm converting is around 6MB to 8MB. Btw, I'm a Premium user.

**Comment by photopea** [comment]
Hi, can you open "milk.sketch", which is in the middle menu of Photopea, and save it as a PSD?

If it does not work, can you disable all browser extensions and try it again?

**Comment by yijuchoo** [comment]
I've tried the milk.sketch file and it works. But my .fig or sketch file doesn't open with the artboards. After it loads the fonts, it shows the loading message and stucks there.
<img width="1257" alt="Screenshot 2020-10-22 at 3 18 52 PM" src="https://user-images.githubusercontent.com/73274892/96838289-47e9c380-147a-11eb-85e1-49771b17cab9.png">

**Comment by photopea** [comment]
So you can not even open your Sketch file properly (without saving a PSD)? Can you send me these problematic files to support@photopea.com ?

**Comment by photopea** [comment]
Hi, there was a bug regarding the Sketch files and I fixed it. You should be able to open your Sketch file and save it as a PSD.

However, your FIG file worked well for me and I was able to save it as a PSD, without any errorw.

Can you confirm, that both files work for you now?

**Comment by yijuchoo** [comment]
Hi, the sketch file I'm able to open it in a breeze & save it as PSD. File can be opened in Photoshop as well. However I still have issue with the Figma file. It still doesn't open. Tried in both browser & application.

**Comment by photopea** [comment]
Can you press More - Use WebGL in Photopea, and then, open your Figma file? 

BTW. you should be asked about scaling the Figma file down, do you confirm it?

**Comment by yijuchoo** [comment]
Tried 1 figma file and it loads fine. Able to save as psd & opening in photoshop no issue. Tried another 2 figma files and both able to load the layers but doesn't display the artboards. Able to save as PSD but when tried to open in photoshop, it said "Could not open “SA2-fig.psd” because the file is not compatible with this version of Photoshop." Current photoshop is 22.0.0 release.

**Comment by yijuchoo** [comment]
oh regarding when asked about scaling, I chose to keep the original dimensions. I did check on Use WebGL before saving as PSD.

**Comment by photopea** [comment]
Hi, if you can not see the preview of your file in Photopea, disable the WebGL (More - Use WebGL) before opening any file.

I converted your FIG files to PSD and Photoshop still can not open them. I see a message "Scratch disk is full" in Photoshop.

However, when I delete half of artboards in Photopea, the PSD works well in Photoshop. Your file has 77 artboards and maybe it is too much for Photoshop.

**Comment by photopea** [comment]
So in short, I think it is a bug in Photoshop, which can not handle PSDs with too many large artboards.

Try to decrease the number of artboards to 20 - 30 and it should work.

**Comment by MichalSZZ** [comment]
@photopea maximum canvas size in Photoshop is 30 000 x 30 000 px https://helpx.adobe.com/photoshop-elements/kb/maximum-image-size-limits-photoshop.html

BTW. there is maximum number of layers too - I think that is something above 5 000 (I had that situation when I wanted to duplicate ca. 40 artboards  with maaaany layers)

**Comment by photopea** [comment]
@yijuchoo so that is why you could not open your PSD in Photoshop. As you decided to keep the original dimension, the height of your PSD was over 30 000 px, which Photoshop can not open.
