### ISSUE TITLE
Pressure Sensitivity does not work when Mapping is set to Mouse

### ISSUE THREAD

**Issue by Saregona** [photopea/photopea#2574]
Hello. 

Wacom Intuos tablet - most current drivers

Have tried on Chrome and Edge, no dice. I seem to get a little bit of transparancy difference, but no size change with differing pressure. 

Works perfectly when mapping mode is set to Pen - but I don't use the Pen mode as I don't like it. Could Pressure Sensitivity please be implemented on the Mouse mapping mode too please? 

Let me know if you need any more info. 

![image](https://user-images.githubusercontent.com/73805551/97823126-fd2a4000-1cf2-11eb-88bc-4079e501453c.png)
![image](https://user-images.githubusercontent.com/73805551/97823144-09ae9880-1cf3-11eb-8cfe-c96ee7d86b88.png)

**Comment by photopea** [comment]
Hi, I did not know that tablets have a pen and a mouse mode.

If you switch to a Mouse mode, is there any program which can still detect the pressure of the tablet? I just want to know if it is possible.

**Comment by Saregona** [comment]
Hi mate, yes I use Mouse mode on my home PC when I am drawing/painting in Photoshop CS5, and I've used other versions of PS with mouse mode and it also works with pressure sensitivity. 

If you need any more information please let me know.

**Comment by photopea** [comment]
I think it is fixed now. Could you please check?

**Comment by Saregona** [comment]
![image](https://user-images.githubusercontent.com/73805551/98070131-82505900-1e9b-11eb-8cb7-0852c6635bf7.png)

Hello, I tried again this morning, still not working for me.

**Comment by photopea** [comment]
Are you sure? That is really strange. Can you update your browser?

**Comment by Saregona** [comment]
I have Version 86.0.4240.183 (Official Build) (64-bit) - which I think is the most up to date after having a quick look - running already.

**Comment by photopea** [comment]
Hi, could you try to use your pen here: https://jsfiddle.net/1jzog2c0/ ? Just draw into the white area. The textbox should show the pen pressure. Does it always show the same value?

**Comment by Saregona** [comment]
It just reads as a constant 1 on Mouse mapping mode. On Pen mapping mode I get different values.

Is it possible that in mouse mode it's prioritising the pen tip as a click first and foremost and ignoring the pressue input somehow? The pen tip is also set to be a left click - and you can't remove this setting.

![image](https://user-images.githubusercontent.com/73805551/98181882-59819f80-1f3f-11eb-971d-dc5640673de5.png)

Im not a programmer, but it was just an idea that popped into my mind.

**Comment by photopea** [comment]
Hi, I changed it a bit, could you try it again here: https://jsfiddle.net/70trv4b8/  ? If it does not work, I will report it as a bug in Chrome.

Do you have any other browsers? Could you try it in them?

**Comment by Saregona** [comment]
I was fiddling in Edge while I was waiting on your reply:

![image](https://user-images.githubusercontent.com/73805551/98183306-d7937580-1f42-11eb-941b-a3613e9998e4.png)

Amazingly good to draw in, but sadly no pen pressure in Edge either :(

**Comment by Saregona** [comment]
No go in JSFiddle :( Get a different value this time, 0.5, but still constant. Gives the same value when I click using the buttons on the side of the pen.

**Comment by photopea** [comment]
I am afraid we can not do anything about it. It should be fixed in a browser (as Photopea gets hadrware input through a browser).

I reported it here: https://bugs.chromium.org/p/chromium/issues/detail?id=1145884
