### ISSUE TITLE
Font not working

### ISSUE THREAD

**Issue by macgavin** [photopea/photopea#2746]
The Doppio One font (Regular, 17pt, Strong, Warp) is typing as an underscore instead of characters. This is from a file I created using this same font on December 15 2020, and am working on again today on January 12 2021.

**Comment by mightyjadey** [comment]
Same issue here. Kidly resolve this issue ASAP photopea

**Comment by lonestarsun** [comment]
Also having the same problem!

**Comment by evanstektchr** [comment]
Ditto.

**Comment by photopea** [comment]
Hi, I am very sorry, it is fixed now.

**Comment by evanstektchr** [comment]
It isn't, though.

**Comment by macgavin** [comment]
I confirm it still isn't working. I am hoping it will take a few minute to resolve. Photopea, when an issue is resolved, how long does it take to process the solution?

**Comment by photopea** [comment]
Try to reload Photopea multiple times. Your browser is probably still showing you the old Photopea from 30 minutes ago. Load a current version of a website.
