### ISSUE TITLE
Context menu in layers issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#3096]
Context menu is not closed/hidden in layers window when changing layers.
For example I can right-click Gradient Overlay and after that click on background layer and select "Create layers" in context menu causing error as seen on screenshot.
![image](https://user-images.githubusercontent.com/6370548/113822086-489eb980-977d-11eb-9b43-f3410949e54a.png)
Other example of error: right-click on text layer - then switch to non-text layer and then select "Convert to Point Text" function.
![image](https://user-images.githubusercontent.com/6370548/113822701-0fb31480-977e-11eb-9c53-8b22433b0291.png)

**Comment by photopea** [comment]
Fixed, thanks for reporting :)

**Comment by hxim** [comment]
Context menu is still not closed/hidden in layers window when new layer is created or deleted or new folder is created via buttons in the bottom of Layers window. Also it is not closed when changing layer by going back in history via clicking in History window.
![image](https://user-images.githubusercontent.com/6370548/114077059-ad563300-98a7-11eb-93da-34857d2bb695.png)
![image](https://user-images.githubusercontent.com/6370548/114077176-cbbc2e80-98a7-11eb-898a-2bdf923a4c7b.png)

**Comment by photopea** [comment]
It should all be fixed now, thanks :)
