### ISSUE TITLE
"Merge down" error

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#325]
Open pea.psd
right-click layer "Blog & Twitter"
select "Merge down"
->
Uncaught TypeError: Cannot read property 'add' of undefined
    at vp.JY (pp.js:3410)
    at At.qu (pp.js:3530)
    at At.qF (pp.js:3529)
    at At.JJ (pp.js:3475)
    at At.Jq (pp.js:3477)
    at Ap.HK._X (pp.js:2879)
    at vH._X (pp.js:5767)
    at vH.vZ.Q (pp.js:6)
    at vH.U.Q (pp.js:4047)
    at va.U.Q (pp.js:4047)

**Comment by photopea** [comment]
Ok, I fixed it (so there is no error). But it is not clear, what should happen in this case (when the layer below is on the other "depth").

**Comment by bhch** [comment]
@photopea The "Merge Down" error still exists. I get this error:

```
pp.js:1541 Uncaught TypeError: (w[p] + "").padStart is not a function
```
