### ISSUE TITLE
Bug Report:  Problems with RAW file format Import and Export

### ISSUE THREAD

**Issue by canaryjohn** [photopea/photopea#3487]
Use Photopea for .raw unity heightmap editing.

Couple of issues seem to have cropped up in the last 2 weeks approximately.

1. Files on import now showing as filename.raw.psd instead of .raw
2. When exporting the original imported raw, and then bring that back into unity it is not the same file as was exported resulting in lumpy and incorrect geometry on our terrains.

Loom video linked showing the problem. We have a gorup of golf course design enthusiasts creating 3d environments in Unity and have have multiple users reporting this issue ove the last 10days to 2 weeks, where previously it all worked well

Thanks for your time

https://www.loom.com/share/0dc4a8e4b8694f6a902ed14b8e317e28

**Comment by photopea** [comment]
Photopea converts every opened file to a PSD, and then, converts a PSD to any other format. There is no other way, Photopea can work only with PSD files inside.

Photopea does not support 16-bit workflow at the moment. It "truncates" your image to 8 bits, and then, it fakes extra 8 bits with zeros when you export it to RAW. We need to add 16-bit support first, as described here: https://github.com/photopea/photopea/issues/3417

**Comment by photopea** [comment]
I fixed it a little, does it work better now?

**Comment by canaryjohn** [comment]
Sadly this issue still remains. It woudl appear it does have to do with the lack of 16bit workflow. Im assure by users that this did work in the past, but I have my doubts now, as if it is indeed the 8bit nature of photopea thats causing the problem then I cant imagine it ever could have worked

**Comment by canaryjohn** [comment]
Probably shouldn’t have edited my comment above, had 3 guys check now and previous projects also have the “lumpy ness” that does seem a direct result of no 16bit support.  

Appreciate a difficult question in terms of development, but is this a high priority on your roadmap with view to implementation in the near future, or would I be best pursuing other options in the short term

**Comment by photopea** [comment]
I would love to add 16bit workflow to Photopea in the future. 

Have you thought about applying a gaussian blur to your height map in your game? You could set each height to 60% of that height + 10% of the height of each neighbour point.

**Comment by canaryjohn** [comment]
Tried the gaussian but its still not quite what we need. Hopefully 16bit arrives soon and can steer the guys back to photopea as a great option for them, for now looks like stuck with photoshop sadly

**Comment by photopea** [comment]
@canaryjohn Photopea supports 16-bit and 32-bit images now https://blog.photopea.com/photopea-5-6-advanced-color-depth.html
