### ISSUE TITLE
Color Range / Save As not working?

### ISSUE THREAD

**Issue by FSY2021** [photopea/photopea#3579]
hi there, it seems that Color Range and Export As buttons are not working at the moment?

**Comment by photopea** [comment]
It should be fixed now. Can you reload Photopea with Shift+F5?

**Comment by FSY2021** [comment]
hi, it is still not responding. i am not sure what's happened

**Comment by photopea** [comment]
Try Photopea in Incognito, or wait an hour.

**Comment by FSY2021** [comment]
thank you. it is back now!
