### ISSUE TITLE
Type Tool problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#365]
Without opening any file I tried to use Type Tool
I attempted to change font or font size
->
pp.js:2435 Uncaught TypeError: Cannot read property 'i' of null
    at j.QL.av (pp.js:2435)
    at iA.pv (pp.js:5929)
    at iA.pV (pp.js:5915)
    at iA.Rm.G (pp.js:6)
    at iA.h.G (pp.js:4151)
    at ia.h.G (pp.js:4151)
    at r_.h.G (pp.js:4151)
    at nV.h.G (pp.js:4151)
    at nV.xe (pp.js:4349)
    at nV.By (pp.js:4359)

**Comment by photopea** [comment]
Fixed. Thank you for reporting it!

**Comment by hxim** [comment]
@photopea 
If a use "Warp" button it still shows this error in this case (no file opened)
->
Uncaught TypeError: Cannot read property 'b' of undefined
    at $.ZO.an (pp.js:2435)
    at KT.UL (pp.js:5908)
    at KT.KD.o (pp.js:6)
    at KT.B_.o (pp.js:4163)
    at Ka.B_.o (pp.js:4163)
    at bG.B_.o (pp.js:4163)
    at bG.wQ (pp.js:5598)
    at BO.KD.o (pp.js:6)
    at BO.B_.o (pp.js:4163)
    at BO.AM (pp.js:4242)

**Comment by photopea** [comment]
Fixed. Thank you!
