### ISSUE TITLE
Request: Remove patterns

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#3914]
Every time opening pattern menu after opened Photopea, we have to load these patterns that we rarely use. 
![Screenshot_20211101_114347_com microsoft emmx](https://user-images.githubusercontent.com/79258245/139619855-94905bc2-a341-431f-a54c-ee94b9a686fd.jpg)

Can you remove them or put them into sub menu? like the brush menu do.
![Screenshot_20211101_114409_com microsoft emmx](https://user-images.githubusercontent.com/79258245/139619865-e6ce178e-7767-4a99-a51c-da113204d68c.jpg)

**Comment by nothingshiru** [comment]
Only need one simple pattern as a default example pattern.

**Comment by MichalSZZ** [comment]
> 
> 
> Only need one simple pattern as a default example pattern.

I have opposite opinion about default patterns, brushes, gradient etc.
In Photopea it should be many more nice looking and usable default things. 
Not everyone know where to find free gradients, patterns, brushes, swatches etc.
Maybe except brushes - the files are not so big to download...
I must to say - that (maybe I am lazy) I oft use new default gradient sets in Photoshop.

**Comment by nothingshiru** [comment]
> > Only need one simple pattern as a default example pattern.
> 
> I have opposite opinion about default patterns, brushes, gradient etc. In Photopea it should be many more nice looking and usable default things. Not everyone know where to find free gradients, patterns, brushes, swatches etc. Maybe except brushes - the files are not so big to download... I must to say - that (maybe I am lazy) I oft use new default gradient sets in Photoshop.

The pattern menu seems to be different from the others. When opening the pattern menu, you need to wait for the pattern to be loaded.

**Comment by photopea** [comment]
I have fixed it - the set of additional patterns is also cached, and should be accessible offline.

**Comment by nothingshiru** [comment]
If we never opened the patterns menu which means the patterns are not cached, we will still face this problem when using Photopea offline. 

I think it would be better to put this set of patterns into sub menu. Give users the choice of whether to load them.

**Comment by photopea** [comment]
I have fixed it. All patterns take only 63 kB and are loaded right after loading Photopea.

I would like to add more useful sets of patterns, brushes, layer styles ... into the "arrow menu". If you have any such resources, please, let me know. They should be free to use (not stolen) and useful for the majority of users.

**Comment by TikaLich** [comment]
![Capture_2022_10_12_13_21_17_392](https://user-images.githubusercontent.com/96197440/195341369-646e97ac-6b81-41d2-9149-4f205a5d8047.png)

I want to delete all exitng patterns (style), but when open the program agian, they come back again
waht to do to delete them once and for all
and sorry for my bad english
thanks

**Comment by photopea** [comment]
You probably have them in your Local Storage. Go to Edit - Local Storage, delete your ASL files there.

**Comment by TikaLich** [comment]
> You probably have them in your Local Storage. Go to Edit - Local Storage, delete your ASL files there.

thank you so much
