### ISSUE TITLE
Spot Healing Brush problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#399]
new file
select Spot Healing Brush
make line from position above image to position under image
->
pp.js:570 Uncaught TypeError: Cannot read property 'x' of null
    at Object.W.Mj.bbE (pp.js:570)
    at W.Mj.Mt (pp.js:540)
    at O.f$.O.sD.sI (pp.js:2147)
    at O.f$.kA (pp.js:2587)
    at Wp.CL (pp.js:5876)
    at Wp.oT.A (pp.js:6)
    at Wp.p.A (pp.js:4075)
    at Wq.p.A (pp.js:4075)
    at K_.p.A (pp.js:4075)
    at K_.lw (pp.js:5358)

**Comment by photopea** [comment]
It does not happen to me :(

**Comment by hxim** [comment]
@photopea 
hmm now it seems not happening to me too
but try this
1. new file
2. erase some area in the middle with eraser
3. grab Spot Healing Brush and make line from above image to the middle of erased area
->
Uncaught TypeError: Cannot read property 'x' of null
    at Object.$.tZ.TMF (pp.js:570)
    at $.tZ.tr (pp.js:540)
    at z.LV.z.vc.vK (pp.js:2146)
    at z.LV.xC (pp.js:2586)
    at $e.lD (pp.js:5876)
    at $e.sn.l (pp.js:6)
    at $e.a.l (pp.js:4075)
    at $m.a.l (pp.js:4075)
    at Mi.a.l (pp.js:4075)
    at Mi.Od (pp.js:5358)

**Comment by hxim** [comment]
more info: I found out it happens only when the line is perfectly vertical....

**Comment by photopea** [comment]
It should be fixed now. Thank you!

**Comment by hxim** [comment]
@photopea 
I just tried and there is still error. See this screenshot:
https://imgur.com/5ux6mEl

**Comment by photopea** [comment]
Now it should be fixed.

**Comment by hxim** [comment]
@photopea 
Unfortunately it still crashes sometimes:
https://imgur.com/UMa8g6z

**Comment by photopea** [comment]
now it should be fixed for good. Thanks!
