### ISSUE TITLE
Text rectangle rotate issue

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#402]
I pressed number while rotating rectangle for Constrained text.
It confirms text and changes opacity of layer to number I just clicked.
Then I released mouse and clicked any key after that
->
Uncaught TypeError: Cannot read property 'add' of null
    at u.qX.qd (pp.js:2369)
u.qX.qd @ pp.js:2369
pp.js:2364 Uncaught TypeError: Cannot read property 'add' of null
    at u.qX.qw (pp.js:2364)

**Comment by photopea** [comment]
It should be fixed now.

**Comment by hxim** [comment]
@photopea 
Not fixed for me :(
Now it says:
Uncaught TypeError: Cannot read property 'add' of null
    at _.Rc.Rd (pp.js:2364)

**Comment by photopea** [comment]
Can you please be more precise, what key did you press? I can not reproduce it.

**Comment by hxim** [comment]
I first open new file.
make text rectangle and rotate it by bottom right corner
(screenshot: https://imgur.com/Dwfm55I)
While I still hold left mouse button in this position i clicked number "1" on my keyboard
(Rectangle now disappears)
Now I released left mouse button
(Type Tool and Layer Opacity Change is written to history window)
Now I clicked number "1" on my keyboard again
->
error appears as seen on this screenshot
https://imgur.com/7wm7Nds

**Comment by photopea** [comment]
Thank you! now it should be fixed.

I was testing it with the Alt key, didn't try to press any number key again.
