### ISSUE TITLE
Free Transform number key problem

### ISSUE THREAD

**Issue by hxim** [photopea/photopea#404]
There is still similar problem or problems to issue #402 but connected to Free Transform

1.I first open new file.
2. Select Rectangle with Rectangle Select
3. Change to Crop Tool
4. Free Transform - rotate it by bottom right corner
While I still hold left mouse button in this position i clicked number "1" on my keyboard
Move with mouse cursor
Now I released left mouse button
->
Uncaught TypeError: Cannot read property 'QH' of null
    at r.JI.QH (pp.js:2205)
    at Dx.SI (pp.js:5878)
    at Dx.gA.g (pp.js:6)
    at Dx.x.g (pp.js:4076)
    at Dc.x.g (pp.js:4076)
    at wP.x.g (pp.js:4076)
    at wP.Jk (pp.js:5359)

Also if you do the same and instead of Crop Tool you select Brush in step 3 it causes different issue -
 Brush is not working after those actions. Maybe there are different problems with other tools selected I didn't try...

**Comment by photopea** [comment]
It should be fixed now. The brush was "not working", because it also changes the opacity of the brush.

**Comment by hxim** [comment]
If you re-open Photopea so Laso Select is never used and perform steps above with Laso Select in step 3 you get this
->
Uncaught TypeError: Cannot read property 'lc' of null
    at W.oQ.AG (pp.js:2403)
    at W.oQ.W.Ab.nu (pp.js:2166)
    at IZ.OA (pp.js:5879)
    at IZ.CG.C (pp.js:6)
    at IZ.Z.C (pp.js:4076)
    at Ic.Z.C (pp.js:4076)
    at bM.Z.C (pp.js:4076)
    at bM.AG (pp.js:5359)
pp.js:2179 Uncaught TypeError: Cannot read property 'F' of null
    at W.oQ.W.Ab.Az (pp.js:2179)
    at W.oQ.getSelection (pp.js:2405)
    at W.oQ.W.Ab.finish (pp.js:2170)
    at W.oQ.Ai (pp.js:2404)
    at W.oQ.W.Ab.nl (pp.js:2170)
    at IZ.OA (pp.js:5879)
    at IZ.CG.C (pp.js:6)
    at IZ.Z.C (pp.js:4076)
    at Ic.Z.C (pp.js:4076)
    at bM.Z.C (pp.js:4076)

**Comment by photopea** [comment]
Hi, it was fixed. I also tried this with other tools in step 3 and everything seems to work fine.

**Comment by hxim** [comment]
Not fixed for me I tried it with Laso Select and it is showing this errors when I move with mouse cursor in above sequence of steps
->
pp.js:2403 Uncaught TypeError: Cannot read property '_W' of null
    at h.pg.pc (pp.js:2403)
    at h.pg.h.pH.GX (pp.js:2166)
    at fn.Xw (pp.js:5879)
    at fn.aS.a (pp.js:6)
    at fn.n.a (pp.js:4076)
    at fJ.n.a (pp.js:4076)
    at Fd.n.a (pp.js:4076)
    at Fd.pc (pp.js:5359)
h.pg.pc @ pp.js:2403
h.pH.GX @ pp.js:2166
fn.Xw @ pp.js:5879
aS.a @ pp.js:6
n.a @ pp.js:4076
n.a @ pp.js:4076
n.a @ pp.js:4076
Fd.pc @ pp.js:5359

**Comment by photopea** [comment]
You are right, I released the mouse right after releasing number 1 (without moving the mouse in between). Now it should be fixed.
