### ISSUE TITLE
Last used color in color picker does not have the same color in shape fill color

### ISSUE THREAD

**Issue by MichalSZZ** [photopea/photopea#4044]
![obraz](https://user-images.githubusercontent.com/38118273/143726286-ed92366a-4006-4c48-b609-05d2638fe758.png)

**Comment by photopea** [comment]
I have fixed it. Now, these "last colors" are the same everywhere. They adapt to the current foreground color, current shape fill color, or current shape stroke color, depending on what was changed as the last one.

Also, I disabled the "live preview" while you change the shape fill color, because if we change the shape fill style 50x a second, the list of last colors contains almost identical colors.

**Comment by nothingshiru** [comment]
@photopea 
Live preview and the problem still exist if we change the color of shape through properties panel.

**Comment by photopea** [comment]
So do you want us to disable the live preview there, too?

středa 1. prosince 2021 nothingshiru ***@***.***> napsal(a):

**Comment by nothingshiru** [comment]
I would like to have the live preview if the problem in the list of colors can be solved.

**Comment by photopea** [comment]
I am afraid we can not have both.

středa 1. prosince 2021 nothingshiru ***@***.***> napsal(a):

**Comment by nothingshiru** [comment]
Well, you might as well disable it.

**Comment by nothingshiru** [comment]
I'm curious why the color fill layer has live preview but there's no such a problem in the list of  colors.

**Comment by photopea** [comment]
In Properties, you change a fill of a current layer (a fill layer must be selected).

In vector drawing tools, you set the "global fill color", which is applied to possibly selected shapes, and will be applied to future shapes. The global fill color is tracked by the "color history".
