### ISSUE TITLE
Warp doesn't work properly with shapes

### ISSUE THREAD

**Issue by nothingshiru** [photopea/photopea#4072]
### "Warp" doesn't work properly on these 2 types of shape.

**1. The irregular shapes that are created by Pen, Curvature Pen.**

When warp such a shape, the shape would become smaller a bit at the moment you drag the control points or the handles.

**2. Rectangle.**

When warp a rectangle that created by **Rectangle** tool, the control points don't work.

When warp a rectangle that created by **Pen, Line, Parametric Shape, etc**, the control points and the handle don't work.

The way to create a rectangle by **Pen, Line, etc.**
1. Create 2 vertical Guides and 2 horizontal Guides.
2. Create a shape, as long as has 4 anchors.
3. Drag the anchors to the intersection points of Guides.
![screenshot_20211205_175402](https://user-images.githubusercontent.com/79258245/144741919-c2c813d0-7a2c-4213-8df6-a43c5320a61d.jpg)

**Comment by photopea** [comment]
Is it fixed now?

**Comment by nothingshiru** [comment]
The control points inside rectangle still don't work. 

And now too many redundant anchors would be added after warped a shape.
For example I warp a rectangle, even if I just drag the top-right point and the edges of the rectangle are still straight lines, a lot of anchors are added but they are doing nothing actually. It would be a problem for editing the shape later.

**Comment by photopea** [comment]
That is how the Warp Transform works. Moving the "points inside" will only transform the content inside. But a rectangle vector shape has no content inside, the points are only on the perimeter.

I think it is not possible to warp long bezier lines properly, without adding points in between.
