### ISSUE TITLE
Adjust transformation movement when rotated

### ISSUE THREAD

**Issue by TheRadicalDreamer** [photopea/photopea#4515]
It would be great to have the movement of layers adapt to the current rotation position.

For example, i have turned my canva 180 grades and when i move layers around with the arrow keys, left is right, right is left, up is down and down is up, which is uncomfortable.

For other angles that are not multiples of 90, maybe it could follow the rules of movement of the more near one, your brain can handle that easily.

**Comment by photopea** [comment]
I have implemented it. But I am not sure if it is the right behaviour. The X and Y axis of the image are clear, and maybe the layers should move along these axes.

**Comment by TheRadicalDreamer** [comment]
It is good~!

You have the move tool that adjusts on each angle, but when you activate Transformation (Ctrl+T) it follows the X&Y axis. So you still have a tool that makes sense when you want to position something specifically on a certain point of the canvas
