### ISSUE TITLE
Ads

### ISSUE THREAD

**Issue by PyroPlumis** [photopea/photopea#4596]
I have several ad blockers on my Chrome, but I have all the settings adjusted so that they're not enabled on Photopea, and for over a year now I've had ads on Photopea and no problem. I still have all the ad blockers disabled on Photopea, I still see the ads, only now I keep having popups telling me that I have ad blockers on. Nothing's changed, the ads are there, I haven't downloaded any new ad blocker or enabled any. Why am I getting these popups suddenly?

Picture of the fact I have the ad there:
![image](https://user-images.githubusercontent.com/105137645/167279222-b7f9732f-5eac-4460-8f84-81a919cfc670.png)

Picture of the fact I have this ad blocker disabled:
![image (1)](https://user-images.githubusercontent.com/105137645/167279241-936bd4f7-15ff-499a-b4d7-a96fea353a91.png)

Picture of the fact I have this ad blocker disabled:
![image (3)](https://user-images.githubusercontent.com/105137645/167279255-1cb8408f-62a0-4012-93a7-d5bd3befc4da.png)

Picture of one of the three messages I get about supposedly having an ad blocker on, despite there being an ad to the right that is very clearly not blocked.
![image (2)](https://user-images.githubusercontent.com/105137645/167279262-1e0c5b1c-3e9e-4cc0-b246-e85ac9f4e28c.png)

**Comment by photopea** [comment]
This "ad" for Photopea premium is shown to people with ad blockers. It is not making us any money. You were blocking ads in Photopea for over a year.

I think one of your ad blockers is lying to you. They say they are disabled, but actually are not. Please, try to turn off all your extensions (temporarily) in about://extensions and see what happens.

**Comment by ijstanley** [comment]
I found this issue too, disabling the blocker and closing/reopening the tab doesn't fix the problem. I run localStorage.clear() in the dev console and cleared the site's cookies, the ads then displayed and the message went away.

**Comment by ijstanley** [comment]
...having fixed the issue, I've just opened the site again and am seeing the placeholder ads and getting the messages.

**Comment by djbacon** [comment]
Same problem here. I use Brave with uBlock Origin. I have disabled both Brave ad blocker and Ublock Origin for photopea sites, but I see placeholders and have popups.
I cannot uninstall adblockers, because a lot of sites are unusable without adblockers, it's safer and it's using less bandwidth (it's important when I'm at my coutryside with mobile internet).

Is there any other solution? 
How is that other websites show ads when adblockers are disabled, but yours doesn't?

**Comment by ijstanley** [comment]
- AdBlock behaves as expected on other sites, pausing it for the individual site shows ads successfully.
- Only when using Photopea do I need to pause AdBlock on all sites for the ads to display.
- AdBlock isn't the only ad blocker that exhibits this behaviour on Photopea, see the other commenter who's using Poper Blocker.

Dismiss my input if you wish, but I'm only trying to help you earn more money, I like Photopea and don't want it to go away. Bothering people to disable their ad blockers when they've already done so is only going to drive users away.

**Comment by photopea** [comment]
Are you sure that on other websites, you see ads of that website? Maybe your adblocker is replacing ads with their own ads, which make them money.

**Comment by ijstanley** [comment]
Yes, they're Google ads, the same as on Photopea.

**Comment by photopea** [comment]
I am afraid it would be too much work for me to create mechanisms to distinguish "good" and "bad" ad blockers.

If we notice, that the URL of our ad provider is blocked, we consider it to be ad blocking.

I mean in your case, an ad blocker could be repacing the original ad code with their own ad code, which makes them money. The ad blocker is getting paid, not the site creator.

**Comment by ijstanley** [comment]
OK, I give up trying to help you out.

My parting comment is, if the AdBlocker were adding its own ads when paused, why is it not doing so on Photopea?

Have a nice day.

**Comment by photopea** [comment]
BTW. I have tried AdBlock Plus, and when I disable it on Photopea.com , ads in Photopea work well.

I think your AdBlocker refuses to be "shut down", because they still want to track you, even if you dont want it.

![image](https://user-images.githubusercontent.com/15955558/167889953-0fa307c1-cbe5-4a32-bf95-580c043b07d9.png)

**Comment by ijstanley** [comment]
OK, I'll switch to AdBlock Plus if helps. Strangely, pausing AdBlock once shows the ads but pausing permanently doesn't, so that would indeed point to AdBlock being the problem, but again, the ads show in both cases on the Guru99 site, which points back to Photopea.

I'll sign off here.

**Comment by djbacon** [comment]
P.S. Today ads are showing for me (not the placeholders). So something is fixed. :)

**Comment by photopea** [comment]
I show ads of my games to people with ad block. They still dont make me any money :(

**Comment by djbacon** [comment]
P.S. If i click on placeholder, it leads to "https://www.photopea.com/NaN" that says "Not Found"

**Comment by photopea** [comment]
@djbacon thanks! I fixed it :)
