### ISSUE TITLE
Stroke Path Not Working Right

### ISSUE THREAD

**Issue by symph01c** [photopea/photopea#4741]
Something is wrong with the Stroke Path option. Every time I use it, it leaves gaps in the resulting line art, even in the middle of where the paths are.
![Corrections](https://user-images.githubusercontent.com/107827304/174523943-6eaacf03-5506-45ca-90dd-6e8710511443.JPG)

Side note: it'd be nice if users could have control over which paths to stroke as well as taper the ends like this when using Stroke Path: 
![taper](https://user-images.githubusercontent.com/107827304/174525339-f97507b6-7e83-4831-8fc7-17865d309118.jpg)

**Comment by photopea** [comment]
Hi, it should be fixed now. Let me know if it works. The second feature can not be added to a raster editor, we would need to create a separate app.

**Comment by symph01c** [comment]
That's quite alright. My main concern was with the Stroke Path. Speaking of which, it seems to work a little better. However, the gaps still appear on the ends of paths as seen below:
![Corrections](https://user-images.githubusercontent.com/107827304/175143328-9f8d6f57-6325-44f7-94e9-786de0b3ca84.JPG)

Could it be something on _my_ end?

Another thing I can't help but notice is the lack of an ability to join paths by the anchor points, similar to the Join feature in Illustrator. That would greatly aid in streamlining the creation of linework The closest available features are Merge, except that ends up affecting all paths rather than only the intended ones, and Unite, which only makes multiple paths movable but doesn't connect the points.

**Comment by symph01c** [comment]
Will this work?

https://drive.google.com/file/d/1V7pMd16uvXHWsvT19EI3v7Tq3WKJ3Vo6/view?usp=sharing

**Comment by photopea** [comment]
It should work perfectly now :)

**Comment by symph01c** [comment]
Yes, it works just fine now! Thank you so much!
