### ISSUE TITLE
Copy text data from Text Layer

### ISSUE THREAD

**Issue by GitUser200607** [photopea/photopea#4929]
Its very hard to copy text from Text Layers. Could you add context menu for text layers "Copy text" please?
_Not layer name, but text data inside this layer._

**Comment by MichalSZZ** [comment]
In Photoshop if you right click on layer with Type tool, you have context menu with many features. Photopea doesn't have any.
There isn' such functionality in Photoshop but now, when I'm thinking about it, it isn't bad idea.

A few steps less (in my shortes way I am doing that by clicking 2x on type layer thumbnail and copy/paste selected text). Maybe it will be easier for someone who don't know such a possibility or work on mobile.

**Comment by GitUser200607** [comment]
> In my shortest way I am doing that by clicking 2x on type layer thumbnail and copy/paste selected text).
This way you copy only layer NAME. If the text of the layer is too long, it will not be copied. So we need the tool to copy TEXT data from Text Layer.

**Comment by MichalSZZ** [comment]
Maybe my english wasn't good.
I will try it once again.
If you double click on layer thumbnail (not layer name), you will get all text highlighted in your layer (not layer name). Then you can copy it very fast.

**Comment by GitUser200607** [comment]
It selects text inside the rectangle, and I press Ctrl+C (or Edit->Copy), but there is no text in the clipboard buffer after that. So this is the problem.

**Comment by photopea** [comment]
In my case, there is a text in a clipboard, if you select text and press Ctrl+C. 

I think you use browser extensions, which break Photopea. Could you try Photopea with absolutely no extensions?

**Comment by GitUser200607** [comment]
The same - with no extensions in Firefox the text is not copied to clipboard (text in Russian maybe this is the problem).

**Comment by GitUser200607** [comment]
Strange. I can copy/paste in Google Chrome, but cant do it with Firefox.

**Comment by photopea** [comment]
It should be fixed now. You should be able to copy and paste in all browsers with keyboard shortcuts, or with Edit - Copy, Edit - Paste, Edit - Clear, etc. There is also a context menu at a right-click, too.

**Comment by GitUser200607** [comment]
Still the same and a little bit more:
```
11:39:42.074 doCopy false undefined
11:39:42.074
ReferenceError: ClipboardItem is not defined
    nX https://www.photopea.com/code/pp/pp.js:13610
    rP https://www.photopea.com/code/pp/pp.js:6209
    rP https://www.photopea.com/code/pp/pp.js:13902
    S https://www.photopea.com/code/pp/pp.js:9794
    S https://www.photopea.com/code/pp/pp.js:9799
    acS https://www.photopea.com/code/pp/pp.js:14013
    OW https://www.photopea.com/code/pp/pp.js:13956
    S https://www.photopea.com/code/pp/pp.js:9794
    S https://www.photopea.com/code/pp/pp.js:9799
    S https://www.photopea.com/code/pp/pp.js:9799
    S https://www.photopea.com/code/pp/pp.js:9799
    S https://www.photopea.com/code/pp/pp.js:9799
    OY https://www.photopea.com/code/pp/pp.js:9849
```

Maybe the problem is with Firefox API
>> Firefox only supports readText and writeText for the clipboard. No binary clipboard operations are supported.

**Comment by GitUser200607** [comment]
You can fix it by setting TRUE to the parameter in about:config:
`dom.events.asyncClipboard.clipboardItem`

**Comment by photopea** [comment]
You are right, there are bugs in Firefox when pressing Edit - Copy (with mouse). I think it is because Firefox still did not implement features which Chromium browsers did.

It is a real pain for me to develop a second versoin of my code because of a browser used by 3% of people. Try to convince Firefox to fix it, or switch to a better browser.

Also, Ctrl+C and Ctrl+V works well for copying a selected text in Firefox.
