### ISSUE TITLE
Feature Request: Additional perspective tools

### ISSUE THREAD

**Issue by whycobb** [photopea/photopea#5059]
Howdy, love Photopea and there's one additional feature I'd love to see added.

Photoshop calls it 'Perspective Warp,' and it's sort of the inverse of Photopea's Edit->Transform->Perspective tool. The way it works is you drop four points on your image, and the crooked rectangle they form is then straightened. This is used to remove perspective from photos, the opposite of what Photopea can already do.

A demonstration:
![image](https://user-images.githubusercontent.com/15617711/196441304-81f9b7ee-4d9b-48a6-96b1-a1a55805cc19.png)
The poster on the wall is distorted by the natural perspective of the photo.

![image](https://user-images.githubusercontent.com/15617711/196442044-2808bcef-a278-4989-b4e9-cbf0e2fe0c54.png)
One point placed at each corner of the poster in 'Layout' mode, so that the program knows how the poster is distorted.

![image](https://user-images.githubusercontent.com/15617711/196442789-a5615cfd-5628-48f2-a29e-9fac6fafee3a.png)
Then you switch to 'Warp' mode and drag the points to adjust perspective, or you can ask the program to line them up automatically. You get a perfect head-on view of the poster (at the cost of distorting the rest of the image). You can also add perspective to a flat image with this tool by dragging the guide points _out of_ alignment.

Would love to see this feature added! I've had entire months where this one tool is the only reason I open Photoshop.

**Comment by photopea** [comment]
I think it can be done using our Perpective Crop Tool, did you try it? But it also removes the image outside the quadrilateral.

**Comment by whycobb** [comment]
Ah, I hadn't seen Perspective Crop, that's very close and covers 90% of my own use cases. But I think forcing it to crop in on the selected region is somewhat limiting - Photoshop's un-cropped perspective warp opens up some cool options for photography. Example:
![image](https://user-images.githubusercontent.com/15617711/196481189-723a0769-978f-4cd7-b45c-c4fd6fcce5eb.png)
First skyscraper I found on google images

![image](https://user-images.githubusercontent.com/15617711/196481319-2fc1f6b4-dc20-4fbf-998c-af3c425170a4.png)
Perspective warp used to flatten the skyscraper, creating an unusual composition across the entire image.

This is a little bit like digitally adding the perspective-distortion effects of shifted-lens photography:
![image](https://user-images.githubusercontent.com/15617711/196482281-dfefe364-45d5-44ba-97a9-f7fc6d109547.png)

Another advantage of Photoshop's version of the tool is that you don't have to use it to flatten the image; it also works as an intuitive interface for adding perspective, whereas Photopea's perspective crop only aligns to right angles.

**Comment by photopea** [comment]
It would be very easy for me to create a tool which transforms the image this way.

But in Photoshop, you can draw two or even more rectangles in the "Layout" mode. When you go to the "Warp" mode and move them, the image becomees "bended" (straight lines are not straight anymore). It is not clear to me how it works.

**Comment by camaz** [comment]
I would also like a feature similar to Edit > Perspective Warp in Photoshop. I use it very frequently to ortho-rectify oblique photos of construction documents (blueprints). There are often wrinkles or bends in the paper documents when photographed, and the ability to align and straighten 2-3 perspective frames together is quite useful.

**Comment by photopea** [comment]
@camaz Did you try the Perspective Crop Tool? https://twitter.com/photopeacom/status/1108073561871269888

**Comment by camoody1** [comment]
Any update on this feature request? I san understand the OP's point about the Perspective Crop Tool getting him most of the way there, but leaving out some important options by deleting pixels. Just wondering where you landed on this. If you don't feel the tool is necessary, you could probably just close this ticket with the suggestion of using the Perspective Crop Tool.

**Comment by CxryzNFTs** [comment]
@photopea Are you going to possibly implement this soon? Photopea is lacking this feature and I use it as a daily part of my workflow.

**Comment by muffinV136** [comment]
**Perspective Warp** when?

**Comment by Smirow** [comment]
Hi, any news on this @photopea?

**Comment by photopea** [comment]
I decided to look into it today. I have implemented the rendering method, so if your PSD contains it as a smart filter, and you modify the smart object, the filter should be re-rendered correctly.

I will try to add the tool itself (the user interface for setting up the parameters- quadrilaterals) tomorrow.

**Comment by Smirow** [comment]
Amazing! Seems to work partially, here a document that fails a bit when you re-render: www.photopea.com/#iLLQSjvhw

**Comment by Smirow** [comment]
So it seems that the image is being cropped by its box bounds when resizing/transforming the layer.

**Comment by photopea** [comment]
I have implemented the UI somehow. the tool / filter is available under Edit - Perspective Warp, could you test it out?

**Comment by Smirow** [comment]
The UI seems to work great on my side. However still the same issue when re-sizing the image (Image -> Image Size), or using the free transform tool on the object being wrapped. I can make a quick video if it's not clear.

**Comment by photopea** [comment]
I opened a PSD in Photopea, which has a smart object with the Perspective Warp as a smart filter.

I pressed Image -Image Size - set it to about a half of the old size. The result looks correctly to me.

Is this what you are doing? If not, could you tell me what you are doing?

**Comment by Smirow** [comment]
You could test to resize with this one: [www.photopea.com/#iLLQSjvhw](http://www.photopea.com/#iLLQSjvhw)

The object is being cropped: 
![Image](https://github.com/user-attachments/assets/4bf97dd2-3b4b-406a-b3b0-4f7d7736ab73)

**Comment by photopea** [comment]
okay, it should be fixed now.

**Comment by Smirow** [comment]
Seems to work great now! Thanks! I'll do some more testing.

**Comment by Smirow** [comment]
Looks great. A general comment: some smart filters don't have **blending options** in Photoshop (Perspective Wrap doesn't for example). It's not a big deal to have it in Photopea, but reverse compatibility (Photopea to Photoshop) may be impacted.

**Comment by photopea** [comment]
Okay, I will leave it as it is now.
