### ISSUE TITLE
Exported ABR Files are Enormous 

### ISSUE THREAD

**Issue by camoody1** [photopea/photopea#5281]
I just created two very small brushes and exported those two from Photopea. The exported file was 88MB in size. Is that normal? Does loading those brushes at startup of Photopea just eat up all my memory?

I've got several other ABR files that I have downloaded from the internet that are exponentially smaller in size than the ones created by the Photopea export. One file, for instance, has about 20 large brushes of grass. This ABR file is only 1MB in size. Can you do anything to fix the insane file size of the current Photopea exports?

_Originally posted by @camoody1 in https://github.com/photopea/photopea/issues/5278#issuecomment-1385011438_
            
This new issue is in reference to a recently closed issue that has brought to light a new problem.

**Comment by photopea** [comment]
It should be fixed now. ABR files should be much smaller.

**Comment by camoody1** [comment]
I just tested this and I'm still getting enormous files. In fact, the files are actually slightly larger, now.

I created a simple 30x30px square brush and when I exported the ABR, it was 51.86MB. I exported one of the brushes I created the other day and it also saves as 51.86MB.

I cleared my cache for Photopea and tried again with the same results. 🤷🏽‍♂️

**Comment by photopea** [comment]
How many brushes have you selected before exporting? If you dont select any, it exports all existing brushes.

**Comment by camoody1** [comment]
I only have one brush selected. When I select five brushes to export, the size goes to 55.31MB.

**Comment by photopea** [comment]
I would like to reproduce it myself.

Could you send me all brushes that you are loading? They can be in Edit - Local Storage.

**Comment by camoody1** [comment]
You want to know all the brushes I have Photopea loading at startup? I'm only exporting one brush as my test. It can be a new brush that I just created or one of the other brushes I already have in my brush list.

**Comment by camoody1** [comment]
Here's a [Video of Brush Export](https://youtu.be/42pAKjDRQBo)

**Comment by photopea** [comment]
I tried to do the same thing as you do, but the ABR file is 1.12 kB in size :(

Are you sure you reloaded Photopea? Could you try it in the Incognito?

**Comment by camoody1** [comment]
It feels like whatever change you made hasn't yet propagated to me, yet. 🤷🏽‍♂️

I have reloaded Photopea several times and even cleared the browser cache. I have not tried my PC or Incognito, yet.

**Comment by camoody1** [comment]
Okay. I just tried it in Incognito mode and it worked perfectly. Only 1.12kb file. I then went back to my regular mode browser and still get 51MB. Since this is an Android phone, I have no extensions installed that could be causing me problems. I don't understand it.

**Comment by photopea** [comment]
Could you try to close Photopea and open it again?

**Comment by photopea** [comment]
I am very sorry, there really was another bug in Photopea. It should be fixed now.

**Comment by camoody1** [comment]
Yes sir! That fixed it. I have all my other brushes loaded in, and a single brush export is nice and small, now.

I'm glad we were able to work through it to find the bug.

**Comment by photopea** [comment]
Thank you for your patience! And thanks for answering people here and on Reddit! :)
