### ISSUE TITLE
The Liquify position is offset

### ISSUE THREAD

**Issue by zheng-coder** [photopea/photopea#5539]
When I used the liquefaction function, the position was offset, which is normal in photoshop, and it bothered me a lot

this is in photopea

![image](https://user-images.githubusercontent.com/63221425/232408028-3b51211d-ca23-4fe7-b8e1-8732fb0a8f3c.png)

this is in photoshop
![image](https://user-images.githubusercontent.com/63221425/232408180-16d4a0ec-172e-4bfe-a864-644c7722b404.png)
[02.zip](https://github.com/photopea/photopea/files/11247178/02.zip)

**Comment by zheng-coder** [comment]
this is in photopea
![image](https://user-images.githubusercontent.com/63221425/232409133-1bc5360c-17fb-4eb5-a00f-af2260c63ad9.png)

this is in photoshop
![image](https://user-images.githubusercontent.com/63221425/232409268-cbb00055-eacb-4437-920f-d673d1ab9971.png)

**Comment by photopea** [comment]
Is it painting at a different place than where you paint? Could you try this? https://www.photopea.com/tuts/photopea-doesnt-work-what-to-do/

**Comment by zheng-coder** [comment]
![image](https://user-images.githubusercontent.com/63221425/232486550-065f7248-26ac-4c26-8c3d-b4b3b40ab82f.png)

**Comment by zheng-coder** [comment]
this is psd file
[02.zip](https://github.com/photopea/photopea/files/11250188/02.zip)

**Comment by photopea** [comment]
Hi Zheng,

I am very sorry, it should be fixed now.

**Comment by zheng-coder** [comment]
Thank you very much, but when I changed the content of the smart object, the problem came back

![image](https://user-images.githubusercontent.com/63221425/232661477-997cfefe-a2ec-4676-8af3-f2dc803270d5.png)

![image](https://user-images.githubusercontent.com/63221425/232661535-e60ed124-52e5-456d-827a-8358b3d8253a.png)

**Comment by zheng-coder** [comment]
could it be fixed? This problem bothers me a lot

**Comment by zheng-coder** [comment]
Replacing smart object layers is a great feature, I hope can fix this bug, it has helped me a lot

**Comment by zheng-coder** [comment]
After changing the content of the smart layer, there is also a problem with clicking Liquefaction. This is like a one-time problem. After changing the content of the smart layer, the problem occurs again
![image](https://user-images.githubusercontent.com/63221425/233663237-987159ce-cc22-4591-b0f0-8968c26bdbab.png)

**Comment by jameslija** [comment]
I have the same problem, the displacement of the smart object

**Comment by photopea** [comment]
It should be fixed properly now. Thanks a lot for your patience! :)

**Comment by zheng-coder** [comment]
That was great. Thank you so much

**Comment by zheng-coder** [comment]
I'm so sorry, here I go again, when I delete the image in the smart object and save it as a psd. When I turn the psd back on and replace the contents of the smart object, the problem arises again.

![image](https://user-images.githubusercontent.com/63221425/233964395-44325600-40e1-446c-92cf-36bbdc6faecd.png)
![image](https://user-images.githubusercontent.com/63221425/233964642-588ceff3-45be-47ed-95f8-3665c1cb292b.png)
![image](https://user-images.githubusercontent.com/63221425/233964746-2da70ee6-fba1-4105-942b-bdff42464895.png)
file in this
[origin.zip](https://github.com/photopea/photopea/files/11309100/origin.zip)


The second question
 Another problem came when I reduced the canvas size of the psd and saved it as a psd, and then worked with the small psd
![image](https://user-images.githubusercontent.com/63221425/233966479-fdfd8b65-9a04-415e-99e2-0387f746e550.png)
[smalltest.zip](https://github.com/photopea/photopea/files/11309170/smalltest.zip)

**Comment by photopea** [comment]
Sorry, I dont know how to fix this one :(
