### ISSUE TITLE
Weird Raster mask behavior

### ISSUE THREAD

**Issue by Pt-home** [photopea/photopea#5654]
Hi!
The crux of the issue in the next GIF:
![RasterMask for Transparency](https://github.com/photopea/photopea/assets/29394245/4b9dd380-5e29-45bd-868b-e757c71e2be1)
On the one hand, the mask works correctly with the layer, but working with it as a channel to return the selection along it, as you can see, is incomprehensible - for some reason it considers itself in this case the mask obtained by the grayscale of the entire file, and behaves the same way when duplicating alpha-channel.

**Comment by photopea** [comment]
It is quite confusing to find out what you are trying to express in your video, as it has no sound. At what point do you think the error occured?

What exactly is wrong, and at what point? Could you describe it with words? Also, what does the "crux" means?

**Comment by Pt-home** [comment]
Sorry, my English is poor
The essence  of the problem. I have a file after applying Vectorize Bitmap, many layers of Kind SOLIDFILL. I will rasterize any of them and make it a Bitmap Mask of Transparency. 
Here is a video of hair, for example. The mask looks correct, is correctly displayed on the icon, when you enter its alpha channel, it also looks correct. But trying to click Magic Wand into her white area in the alpha channel to restore the selection triggers something wrong.
The alpha channel behaves as if instead of the white area of the mask, it actually contains a grayscale version of the ENTIRE file, as if all layers were again flattened. Moreover, duplicating the mask channel, I get not the head area, but for some reason this grayscale version of the file as a whole. 
And this is wrong, if the mask touches the hair layer, for example, then it should contain only the hair area, restore the selection of only the hair on the alpha channel of the mask and duplicate it into a new channel as soon as the hair area. 
I even specifically checked the operation of this file in the PS - everything is absolutely correct there...
PPS If my explanation of the problem is again unclear, I can record the video again, but I can voice it in Ukrainian (well, or in Russian) %)

**Comment by Pt-home** [comment]
Video this problem:
[https://youtu.be/p3_cOmPY090](url)

**Comment by camoody1** [comment]
> Video this problem: [https://youtu.be/p3_cOmPY090](url)

This link doesn't seem to work.🤷🏼‍♂️

**Comment by camoody1** [comment]
> Video this problem: [https://youtu.be/p3_cOmPY090](url)

FYI: @photopea This video link doesn't work unless you copy it from his post and paste it directly into the web browser. Something isn't right with how the comment saved here in GitHub. 🤷🏼‍♂️

**Comment by Pt-home** [comment]
> > Video this problem: [https://youtu.be/p3_cOmPY090](url)
> 
> FYI: @photopea This video link doesn't work unless you copy it from his post and paste it directly into the web browser. Something isn't right with how the comment saved here in GitHub. 🤷🏼‍♂️

Yes, I also noticed this problem

**Comment by camoody1** [comment]
@Pt-home I'm not entirely sure why you're doing what you're doing, but did you know that after you've performed the Vectorize Bitmap and then applied a Raster Mask to the layer that you're working on, you can actually right-click on that layer  and choose "Convert to Smart-Object" to _flatten_ that layer? You could then either leave it as a Smart-Object or right-click and Rasterize it. This way, you can just hold the CTRL key and left-click on the layer to select the entire shape. No need to go into the Channel window at all.

Unless, of course, you have some other reason that you're doing everything you're doing. :)

**Comment by Pt-home** [comment]
> Unless, of course, you have some other reason that you're doing everything you're doing. :)

I have some other reason;)

**Comment by photopea** [comment]
I think I have fixed it. Using the Magic Wand on the "mask channel" should work as in Photoshop now :)

**Comment by Pt-home** [comment]
Sorry, but its moment have two problems (in video you can see this). Magic Wand work correctly now, good.
But if I want DUPLICATE this alpha-channel - the problem remains. Copy alpha-channel must be copy, as in PS...

**Comment by photopea** [comment]
Ok, it should be fixed, too. Whenever a raster mask of some layer is active, duplicating the current channel will result into duplicating a raster mask.

Note, that our Channels panel does not work exactly as in Photoshop (you can not un-highlight channels that are raster masks).

**Comment by Pt-home** [comment]
Thanks, дуже дякую:)
