### ISSUE TITLE
Photopea is changing colors after just uploading

### ISSUE THREAD

**Issue by FrAPo777** [photopea/photopea#6045]
Your Operating System: Windows 11 PRO
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Upload any photo
3. Do nothing
4. Save the photo

When I do these steps Photopea will change colors slightly. Like a filter.

There is original photo downloaded from my iPhone and used for editing:
[Original photo.zip](https://github.com/photopea/photopea/files/12643668/Original.photo.zip)
There is photo after downloading it from Photopea (no editing done)
[Photo after downloading.zip](https://github.com/photopea/photopea/files/12643670/Photo.after.downloading.zip)

**Comment by camoody1** [comment]
@FrAPo777 The "after" has a bit of a pink tinge to it, right? I can definitely see the difference.

**Comment by FrAPo777** [comment]
@camoody1 Yes thats exact. Pink/purple tint.

**Comment by photopea** [comment]
I have fixed it.

Your file has an attached ICC color profile. It is named "sRGB", so Photopea was ignoring it. But in fact, it is not sRGB (but looks similar).

Now, Photopea will detect and use the attached ICC color profile, even if it is named "sRGB" (the default color space of Photopea).

**Comment by FrAPo777** [comment]
Hi Im sorry but still the same issue. I tried it right now :/

**Comment by photopea** [comment]
Did you reload Photopea in between? Also, when you export a JPG, do you enable "convert to sRGB"?

**Comment by FrAPo777** [comment]
Yes I did reload Photopea. When I export a JPG - two possibilities.
1) If there is a box "convert to sRGB" - I click it and everything is fine.
2) But with 70% of photos there is no box "convert to sRGB".
Adding two screenshots.


![no sRGB box](https://github.com/photopea/photopea/assets/145232691/7d49e202-fb0c-4a0d-a6fe-c95ea48c9b61)
![sRGB box](https://github.com/photopea/photopea/assets/145232691/f70372c2-2ed4-4494-bf4f-583ae21cacaf)

**Comment by photopea** [comment]
I opened your original photo in Photopea and re-exported it as a JPG file (disabled "convert to sRGB"). When I open both images in Windows Image Viewer, I can not see any difference.

Could you share a screenshot of what the difference looks like? There is no "pink tint" anymore in my case.

**Comment by FrAPo777** [comment]
Well I tried to screenshot what I see on my Windows Image Viewer. There are two screenshots. Hope you are able to see it now. I even ZIP them so you can download them.

[Screenshots.zip](https://github.com/photopea/photopea/files/12650107/Screenshots.zip)


![Original photo screenshot](https://github.com/photopea/photopea/assets/145232691/e7ffc0bf-1526-40be-bd43-c7847a7e45c1)
![After Photopea screenshot](https://github.com/photopea/photopea/assets/145232691/e7bc5c8f-4c70-4f98-b1bd-2bbf7a18656d)

**Comment by photopea** [comment]
Could you send me two JPG files : JPG file A, which you opened in Photopea, and a JPG file B, which you got after exporting A as a JPG in Photopea? You say the A looks differently than B, so I will look at them myself.

**Comment by FrAPo777** [comment]
JPG file A
[JPG file A ZIP.zip](https://github.com/photopea/photopea/files/12652278/JPG.file.A.ZIP.zip)
![JPG file A](https://github.com/photopea/photopea/assets/145232691/22d9fec6-2919-4003-a4ec-763ac5a48a21)

JPG file B
[JPG file B ZIP.zip](https://github.com/photopea/photopea/files/12652288/JPG.file.B.ZIP.zip)
![JPG file B](https://github.com/photopea/photopea/assets/145232691/725b88f9-29f0-48a9-bdd6-8fdec8cd9635)

On my PC they are different. Hope you can see it.

**Comment by photopea** [comment]
I would like to point out, that you sent us a file "IMG_8770.jpg" in the past, and the problem was fixed - that file worked fine.

Now, you are sending us a file "IMG_8775.jpg", which we have never seen! I have fixed the problem for this file, too :)

Let me know if you have problems with any other files. But test it with the same files as you send us.
