### ISSUE TITLE
Vector smart object cannot be viewed and resized properly

### ISSUE THREAD

**Issue by kaan-aytekin** [photopea/photopea#6455]
Your Operating System: MacOS Ventura 13.4.1
Your Web Browser: Chrome Version 122.0.6261.57
The problem happens in the Incognito Mode, too: Yes

**This must be done to see the problem**
1. Go to www.photopea.com
2. Download the PSD file from [here](https://we.tl/t-kOFLoD6S5x) and open it on photopea
3. Try to resize (or apply any free transform) the smart object layer and the image disappears.
4. Open the smart object by clicking the layer thumbnail. Under the newly opened "Vector Smart Object-ai.psd" file the layers are listed correctly but image cannot be seen.

**Comment by photopea** [comment]
Thanks, it should be fixed now.

**Comment by kaan-aytekin** [comment]
Thanks for the quick fix! 
I can resize the layer now but still cannot see the image on the opened vector smart object file (step 4 above)
Is that the expected behaviour?

**Comment by photopea** [comment]
Yes, if you open that AI file in Adobe Illustrator, the content is outside the artboard, too. You should ask the author of the file about why does it look this way.
