### ISSUE TITLE
When grouping layers selected by holding cmd, they jump into the folder below

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#661]
[jump.mp4.zip](https://github.com/photopea/photopea/files/1933750/jump.mp4.zip)

Also showed in the video above

**Comment by photopea** [comment]
I believe it has been fixed. Can you try it again?

**Comment by hgs54371** [comment]
Weird thing still happen
Another example 
[jump.still.mp4.zip](https://github.com/photopea/photopea/files/2087429/jump.still.mp4.zip)

**Comment by photopea** [comment]
Now it should be fixed for good :) Thank you very much for not giving up and testing it so many times!
