### ISSUE TITLE
Brush is interfering with image with clicking "Ctrl + Z"

### ISSUE THREAD

**Issue by whiskeredshrimp** [photopea/photopea#6641]
Your Operating System: WINDOWS 10
Your Web Browser: CHROME + APP
The problem happens in the Incognito Mode, too: N/A

This must be done to see the problem

1. Go to [www.photopea.com](http://www.photopea.com/)
2. Open my file
3. Select my brush (my brush is a default preset one) and adjust the smoothness
4. I drag my brush
5. Ctrl + Z to undo
6. When I let go, and move my cursor, it erases my image from another layer.
7. When Ctrl + Z again, it removes the image and I am unable to see the image or cursor. (Also happens to a new file)
 

https://github.com/photopea/photopea/assets/143677276/dd8be946-a3cd-4317-be1f-69c2e55d6dd9

**Comment by photopea** [comment]
I am very sorry, it should be fixed now. Please close Photopea and open it again.

**Comment by whiskeredshrimp** [comment]
Hello, it is still happening 

https://github.com/photopea/photopea/assets/143677276/518609e8-3663-4ed3-8292-0a45a8fe2af6

**Comment by photopea** [comment]
Did you clear your cache? Maybe you are using the old, cached version of Photopea.
