### ISSUE TITLE
Couple issues when using Stained Glass filter with Masks

### ISSUE THREAD

**Issue by Bellum1** [photopea/photopea#6697]
Your Operating System: Microsoft Windows 11 Home
Your Web Browser: Google Chrome
The problem happens in the Incognito Mode, too: (didn't test)

**This must be done to see the problem**
1. Go to www.photopea.com
2. (Context: I was following a youtube tutorial) watch video: 
https://www.youtube.com/watch?v=r-pNf5xVYyM&ab_channel=BlueLightningTVPhotoshop

3. follow tutorial up until **~2:06**. At that point I noticed that applying the stained glass filter didn't fully cover the masked layer (some edges weren't fully tiled, leaving some black area instead:
![thing1](https://github.com/photopea/photopea/assets/143123981/ad25712e-e817-4efc-9d5c-875b0b138c75)

4. continue tutorial until **~5:35**. At this step the top layer's tile-border-pattern was no longer the same as the lower layer's. Could duplicating the mask have caused one of them to re-render and get a new random seed? (uh?) -> (I truly have no idea)
![image](https://github.com/photopea/photopea/assets/143123981/a61d3005-fa14-42a3-a7e1-fc2fafbed300)

So yeah those were a couple issues I had while going through the tutorial. Other than that 10/10 would Photopea again

**Comment by photopea** [comment]
Hi, it should be fixed now :)

**Comment by Bellum1** [comment]
Thanks for your help! The filter now fully covers the edges:

![image0](https://github.com/photopea/photopea/assets/143123981/ac4499cb-32dc-4298-8d8e-cb2e6804ef4f)

Though I am still having issues with step 4 (where the filter pattern seems to change when duplicating the mask):

![image](https://github.com/photopea/photopea/assets/143123981/48fd0ea4-31c4-4d6d-b084-91660ce9ad00)
 
Is there a trick I can use to get around this issue?

**Comment by photopea** [comment]
That should be fixed now, too! No need to use the magic wand, it should work the same as in Photoshop.
