### ISSUE TITLE
HTTP error: 401

### ISSUE THREAD

**Issue by aveonehere** [photopea/photopea#7231]
Your Operating System: Windows11
Your Web Browser: Brave
The problem happens in the Incognito Mode, too: idk

**This must be done to see the problem**
1. Go to www.photopea.com
2. ....
3. ....
4. ....
![obraz_2024-10-11_142724880](https://github.com/user-attachments/assets/6816d375-9241-4290-aea4-a2721d942f00)

email: aveonehere@gmail.com

**Comment by photopea** [comment]
I think I have fixed it, could you try it again?

**Comment by aveonehere** [comment]
Unfortunately, problem still arise

**Comment by aveonehere** [comment]
![image](https://github.com/user-attachments/assets/6a6fd844-e43b-4ff5-b3e6-529cc1d9bebd)


Still the same... I don't know what's going on with it... :/

**Comment by photopea** [comment]
Could you tell me the email address that you see when you open www.Photopea.com and press "Account" at the top?

**Comment by photopea** [comment]
I have to close it, because nobody is responding to me.
