### ISSUE TITLE
your site is down

### ISSUE THREAD

**Issue by parker379** [photopea/photopea#7520]
Your Operating System: Windows
Your Web Browser: Microsoft edge
The problem happens in the Incognito Mode, too:

**This must be done to see the problem**
1. Go to www.photopea.com
2. .... go to open from computer
3. .... try and open a fille
-----------------------------------------------

Other way:
1. Go to www.photopea.com
2. go to new project
3. try and open a project

**Comment by parker379** [comment]
its 10PM and no ones fixed it and i need photopea for ERLC Liveries

**Comment by LupettoLavoretto** [comment]
Same problem since yesterday evening (here in Italy)

**Comment by photopea** [comment]
It was fixed 12 hours ago.

You must close and reopen Photopea, did you try it?

Maybe your computer is caching the old version for some reason (even though it should not do it). Did you try to open Photopea in the Incognito mode?

**Comment by mparmesan** [comment]
Still down this morning. Not working on Firefox, Chrome or Safari. Incognito mode does not solve the issue.

**Comment by photopea** [comment]
What is 13k? Is it 13 000 pixels in width? And what is "photo dragged onto the template"?

**Comment by photopea** [comment]
I have to close it, because the person did not respond :(
