### ISSUE TITLE
stroke freezes page

### ISSUE THREAD

**Issue by kseniyagraphics** [photopea/photopea#7581]
when i apply a stroke photopea freezes and i am unable to edit the image futher

**Comment by photopea** [comment]
I think I have fixed it, could you reload Photopea and try it again?

**Comment by kseniyagraphics** [comment]
yeah no, its still not working on layer styles and continuously freezes.

**Comment by hoody29** [comment]
its happening to me to i try too use blending options and it freezes.

**Comment by photopea** [comment]
Did you restart Photopea?

**Comment by hoody29** [comment]
so did i and its still freezing

**Comment by hoody29** [comment]
oh wait i think it fixed

**Comment by hoody29** [comment]
but why am i getting random popups?

**Comment by hoody29** [comment]
thank you it fixed

**Comment by qrvcz** [comment]
everytime i try to make a design its freezing somehow ;( 

![Image](https://github.com/user-attachments/assets/41c9217b-31f8-4844-8780-d1146b68e2bf) look

**Comment by photopea** [comment]
Maybe send me your file and tell me what you do with it?

**Comment by hoody29** [comment]
yo that pic looks sick

**Comment by photopea** [comment]
I have to close it, because nobody is replying :(
