### ISSUE TITLE
Help with not saving after smart filters?

### ISSUE THREAD

**Issue by tacotaker46** [photopea/photopea#7660]
I'm sorry I don't mean to be unhelpful, I'm not sure how to replicate my issue alone. I would love to send over my file I'm working on if you guys wanna look into it.

It's really halting my progress, my first problems showed up when adding more and more things, ctrl+s wouldn't save anymore. I changed to clicking save as PSD every time and that worked. But after a while again, any time I wanted to use an Image -> Adjustment anything, it would stop saving at all. Just stuck with the "Saving" icon on the top of the page. 

I had the problem once and thought it was one file that was saved too many times, so I worked on an entirely new file and now it's the same issue. When I make a brand new one, everything saves fine if it's a few layers and such. But as soon as it's filled up like the file I have now, it stops saving :(

I'm willing to help with anything I can do. I'm sorry I'm not the most skilled in bug fixing. I cant seem to replicate the problem other than adding lots of layers and images and such. Thanks for reading!

(It says I cant put the PSD file here, so if it's alright I put it in a google drive: https://drive.google.com/file/d/1_riWjCvkPdph9gZGgA50QnhJ0CpOBABA/view?usp=sharing)

**Comment by tacotaker46** [comment]
So I realized I can open the image I wanna adjust in a new workspace, then just drag it over to my main file. Not ideal but I'm happy I'm not stuck stuck!

**Comment by photopea** [comment]
There was a problem with loading 32-bit PSD files with smart objects. I have fixed it. Could you try it again?

**Comment by photopea** [comment]
I will close it, as I think it is fixed now, but we can keep discussing it.

**Comment by tacotaker46** [comment]
Hey sorry can't check it this instant, but thanks for replying! I'll let you know :D

**Comment by tacotaker46** [comment]
Hey i'm sorry, it's still not working for me :(

I reset my computer and browser and etc as well. I'm not sure why it's not saving still. I'd love to help still with anything you guys need.

**Comment by photopea** [comment]
Could you describe some steps that I need to do to see a problem?

**Comment by tacotaker46** [comment]
With my file, I insert a new image or take an existing one from a layer. I use the image adjustment, and I also found with any blur filter attached, it doesn't save at all it get stuck. I can see if I can replicate it from a new file and try and let anyone find the problem. Otherwise I can send a short video of what it looks like on my screen if you'd like.

Edit: I just copy and pasted all my layers into a new project and everything is working fine now. Possibly something with saving on one file too many times?

**Comment by tacotaker46** [comment]
I FIGURED IT OUT!!! You have to rasterize the image before saving it and making adjustments/filters. 

At least I think this is the only way to solve it. I filmed myself trying to show it not saving, but the first time I did I didn't realize it asked me to Rasterize the image first. I just shrugged and oh well, then it saved and I was confused. After filming it a second time to show what I've been dealing with, only then did I realize it never asked me to rasterize the image. 

After doing that, it worked and it let me save and everything! I guess without realizing, me and maybe some others won't think to rasterize the image and give up before trying to solve the problem. I'm gonna post a link to show what was happening with it not saving, but thanks for responding! I hope this helped, maybe you guys can fix the bug that doesn't let the prompt show up? Not to rude, this is your guys' territory haha.

(Video showing it not working: https://www.youtube.com/watch?v=8YB9B5frluM)

**Comment by photopea** [comment]
I was able to see a problem: I opened "Mk 2 Overlay Making.psd", I "drag-and-dropped" a JPG file into it, and applied the Curves adjustment (as a smart filter on a smart object) to it. When saving as a PSD, the PSD was 0 Bytes in size.

It should be fixed now. Do you still have any problems?

**Comment by tacotaker46** [comment]
I'll check it out later today after work thanks again!

**Comment by tacotaker46** [comment]
Hey i'm so sorry I was out of town for 3 days and couldn't bring my PC. I totally forgot to do this! It's working now thanks so much!!
