### ISSUE TITLE
Undo keyboard shortcut don't work anymore

### ISSUE THREAD

**Issue by MaxiPaille** [photopea/photopea#842]
Hello,

It seems that Undo command keyboard shortcut don't work anymore. (I tried under Chrome and Firefox)
Ctrl-C, Ctrl-V seems to work. Ctrl-k works too.

Do you have any idea?

Thanks

**Comment by MaxiPaille** [comment]
Hihi,
I'm french, so my keyboard is AZERTY.
Your script detect ["ControlLeft","KeyW"] when I press the Z key.

Unfortunately, i guess Control + W is not catched by a stopPropagation call and try to close the current tab. But if I switch my keyboard to QWERTY en press Control + W, it works as it should.

I wish you strength and courage to fix this little - but so annoying - issue. ^^

**Comment by photopea** [comment]
Ok, I made the physical key W to be understood as Z. It should work now. Also, Q works like A (so you can use Ctrl + A to select all).

**Comment by AcelisWeaven** [comment]
Hi @photopea ,

I'm still having the same issue as @MaxiPaille, using an french azerty keyboard on Chrome. Other shortcuts seems to be working fine. (even Ctrl-A)
By the way, on the fiddle I also see `["ControlLeft","KeyW"]`.

**Comment by photopea** [comment]
Let's discuss it here: https://github.com/photopea/photopea/issues/1071

**Comment by FredVPCrazy** [comment]
Hello,
Yes Right, the application is unfortunately not usable on QWERTY keyboard because it is too slow without cancellation on keyboard, too bad because it would have replaced Photoshop at home it seems.

**Comment by FredVPCrazy** [comment]
on AZERTY !! not QWERY :)

**Comment by FredVPCrazy** [comment]
QWERTY

**Comment by akkolad** [comment]
+1 for the AZERTY support !

**Comment by FredVPCrazy** [comment]
It's OK now for the undo/redo on AZERTY, thanks.

**Comment by MaxiPaille** [comment]
Thanks a lot!
