### ISSUE TITLE
Double tap slider knobs to reset in Firefox

### ISSUE THREAD

**Issue by hgs54371** [photopea/photopea#916]
This has mentioned before, but still not working

**Comment by photopea** [comment]
It works for me in Chrome on Windows and other places.

**Comment by hgs54371** [comment]
On firefox mac it's not working, Also for exposure, photo filter, channel mixer, and Most sliders in layer styles dialog, where the default values aren't located at the middle of the slider, "set to slider center" doesn't work for resetting them to default

**Comment by photopea** [comment]
Ok, I see it is a problem only in Firefox.

**Comment by photopea** [comment]
I fixed it. I also fixed double-tapping on touchscreens.

**Comment by hgs54371** [comment]
In adjustment layers it worked, but it just set to slider center, for values aren't at center by default, they still go center.
As for sliders in layer styles dialog, still not working

**Comment by photopea** [comment]
This works for all sliders, which have a maximum value defined.

Please, specify an exact slider and tell us, which value you want to have after a double-click.

**Comment by hgs54371** [comment]
The ones in exposure, photo filter, channel mixer adj, and Most sliders in layer styles dialog

**Comment by photopea** [comment]
It should work now, but not on mobiles.

When the value is between 0% and 100% (e.g. Opacity), I think it should jump to 50% after double-click.

**Comment by hgs54371** [comment]
Double click in layer style dialog worked now, but the majority of them have a default value that's not at the slider center
